### ISSUE TITLE
When using System.import with webpack 2 and web-dev-server

### ISSUE THREAD

**Issue by aight8** [webpack-contrib/extract-text-webpack-plugin#188]
It happen when use webpack-dev-server with System.import in a bundle file and change a file. Then this error happens:

```
xxx/node_modules/extract-text-webpack-plugin/index.js:22
            if(c.initial) return;
                ^

TypeError: Cannot read property 'initial' of undefined
    at ExtractTextPlugin.<anonymous> (xxx/node_modules/extract-text-webpack-plugin/index.js:22:8)
    at Array.forEach (native)
    at ExtractTextPlugin.mergeNonInitialChunks (xxx/node_modules/extract-text-webpack-plugin/index.js:21:16)
    at ExtractTextPlugin.<anonymous> (xxx/node_modules/extract-text-webpack-plugin/index.js:275:12)
    at Array.forEach (native)
    at ExtractTextPlugin.<anonymous> (xxx/node_modules/extract-text-webpack-plugin/index.js:273:21)
    at xxx/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (xxx/node_modules/async/lib/async.js:236:30)
```

Output chunk.chunks:

```
Chunk {
  id: null,
  ids: null,
  debugId: 1013,
  name: 'text',
  modules: [],
  chunks: [ undefined ],
  parents: [],
  blocks: [],
  origins: [],
  files: [],
  rendered: false,
  entry: true,
  initial: true,
  index: 0,
  originalChunk:
...
```

**Comment by Harryandrew** [comment]
+1 on this...

**Comment by bebraw** [comment]
This could use a little standalone example against `import()`.

**Comment by bebraw** [comment]
Based on the error I would say this is actually the same as #406. The code has changed to `.isInitial()`.

Closing this as a result.
