### ISSUE TITLE
TypeError thrown when trying to generate source map

### ISSUE THREAD

**Issue by michaeldzjap** [webpack-contrib/extract-text-webpack-plugin#239]
This happens for me using webpack 2.1.0-beta.21 and ExtractTextWebpackPlugin -v 2.0.0-beta.3. The following error is thrown:

`TypeError: Cannot read property 'sections' of null at new SourceMapConsumer ...`

with config:

```
devtool: 'source-map',
...
{
   test: /\.scss$/,
   loader: ExtractTextPlugin.extract({ fallbackLoader: 'style', loader: ['css?sourceMap', 'sass'] }),
   include: path.resolve(__dirname, 'resources/assets/sass')
}
```

Without the source map stuff everything works fine.

**Comment by philjones88** [comment]
I get the same on `2.0.0-beta.4` too:

```
ERROR in js/foo.vendor.bundle.js from UglifyJs
TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/node_modules/source-map/lib/source-map-consumer.js:20:19)
    at /Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:64:23
    at Array.forEach (native)
    at Compilation.<anonymous> (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:44:10)
    at next (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/node_modules/tapable/lib/Tapable.js:83:14)
    at Compilation.<anonymous> (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:144:4)
    at Compilation.applyPluginsAsync (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/node_modules/tapable/lib/Tapable.js:85:13)
    at Compilation.<anonymous> (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/lib/Compilation.js:607:9)
    at next (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/node_modules/tapable/lib/Tapable.js:81:11)
    at Compilation.<anonymous> (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/lib/ProgressPlugin.js:114:5)
    at next (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/node_modules/tapable/lib/Tapable.js:83:14)
    at ExtractTextPlugin.<anonymous> (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/extract-text-webpack-plugin/index.js:316:4)
    at Compilation.applyPluginsAsync (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/node_modules/tapable/lib/Tapable.js:85:13)
    at Compilation.<anonymous> (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/lib/Compilation.js:603:8)
    at next (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/node_modules/tapable/lib/Tapable.js:81:11)
    at Compilation.<anonymous> (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/lib/ProgressPlugin.js:110:5)
    at next (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/node_modules/tapable/lib/Tapable.js:83:14)
    at ExtractTextPlugin.<anonymous> (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/extract-text-webpack-plugin/index.js:292:5)
    at /Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/async/lib/async.js:209:22)
    at ExtractTextPlugin.<anonymous> (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/extract-text-webpack-plugin/index.js:244:10)
    at Compilation.applyPluginsAsync (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/node_modules/tapable/lib/Tapable.js:85:13)
    at Compilation.seal (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/lib/Compilation.js:551:7)
    at Compiler.<anonymous> (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/lib/Compiler.js:436:15)
    at /Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/node_modules/tapable/lib/Tapable.js:152:11
    at Compilation.<anonymous> (/Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/lib/Compilation.js:444:10)
    at /Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/lib/Compilation.js:420:12
    at /Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/phil/Documents/Projects/foo/src/FooBarNG2/node_modules/async/lib/async.js:52:16
```

**Comment by cema-sp** [comment]
When trying to build withs sourcemaps, I get:
~~~
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:1228:5)
    at Object.onRender (/Users/cema-sp/ruby/nooscope/node_modules/sass-loader/index.js:282:42)
    at /Users/cema-sp/ruby/nooscope/node_modules/sass-loader/node_modules/async/dist/async.js:2231:35
    at arrayEach (/Users/cema-sp/ruby/nooscope/node_modules/sass-loader/node_modules/async/dist/async.js:1357:13)
    at Object.<anonymous> (/Users/cema-sp/ruby/nooscope/node_modules/sass-loader/node_modules/async/dist/async.js:2223:17)
    at Object.<anonymous> (/Users/cema-sp/ruby/nooscope/node_modules/sass-loader/node_modules/async/dist/async.js:338:31)
    at Object.callback (/Users/cema-sp/ruby/nooscope/node_modules/sass-loader/node_modules/async/dist/async.js:847:20)
    at options.success (/Users/cema-sp/ruby/nooscope/node_modules/node-sass/lib/index.js:309:32)
~~~

**Comment by githoniel** [comment]
the same to me. i had to close css sourcemap

"webpack": "^2.2.0",
"extract-text-webpack-plugin": "^2.0.0-rc.2",

```bash
ERROR in ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-2ef434dc!./~/postcss-loader?sourceMap!./~/vue-loader/lib/selector.js?type=styles&index=0!./posUI/extend/components/layout/src/layout.vue
Module build failed: ModuleBuildError: Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:538:5)
    at Object.<anonymous> (C:\git\QuanMinFu\node_modules\css-loader\lib\loader.js:101:19)
    at Array.map (native)
    at Object.<anonymous> (C:\git\QuanMinFu\node_modules\css-loader\lib\loader.js:99:31)
    at C:\git\QuanMinFu\node_modules\css-loader\lib\processCss.js:200:3
    at C:\git\QuanMinFu\node_modules\webpack\lib\NormalModule.js:141:35
    at C:\git\QuanMinFu\node_modules\loader-runner\lib\LoaderRunner.js:359:11
    at C:\git\QuanMinFu\node_modules\loader-runner\lib\LoaderRunner.js:225:18
    at context.callback (C:\git\QuanMinFu\node_modules\loader-runner\lib\LoaderRunner.js:106:13)
    at Object.<anonymous> (C:\git\QuanMinFu\node_modules\css-loader\lib\loader.js:32:18)
    at C:\git\QuanMinFu\node_modules\css-loader\lib\processCss.js:223:4
```

**Comment by mattlewis92** [comment]
I was getting the same error but fixed it by upgrading to 2.0.0-rc.3 and using the new fallback / use config style: https://github.com/webpack-contrib/extract-text-webpack-plugin/releases

**Comment by MichalZalecki** [comment]
Same happens with:

```js
"webpack": "2.2.1",
"extract-text-webpack-plugin": "2.0.0-rc.3",
```

**Comment by hakimCZE** [comment]
@MichalZalecki worked for me, no error and source maps are generated for css nad js. Thanks 👍

**Comment by ayush-bhandari** [comment]
@MichalZalecki thanks, it was eating my brains out !!

**Comment by bitkicker** [comment]
@MichalZalecki This did the trick. Thank you!

**Comment by scottdj92** [comment]
Thanks @MichalZalecki! Closing issue. Feel free to re-open if the issue persists.

**Comment by zeusbangayan** [comment]
Im using the following:

"extract-text-webpack-plugin": "^2.1.0"
"webpack": "^2.2.1"


and having this issues.

**Comment by codejockie** [comment]
@MichalZalecki thank you, it worked.

**Comment by rwalus** [comment]
@MichalZalecki You are awesome!  I'm glad I got here!
ps. Dzięki Michał! Po 2h walki cieszę się, że tutaj dotarłem!

**Comment by lowesusannah** [comment]
@MichalZalecki Your fix is still working in 2018 -- thank you so much!
