### ISSUE TITLE
Extracting to separate file via import throws error

### ISSUE THREAD

**Issue by MartinMuzatko** [webpack-contrib/extract-text-webpack-plugin#277]
Hello there! 

I'm currently trying to separate my css into its own file.
I used a similar setup as described [in the official docs](https://webpack.github.io/docs/stylesheets.html#styles-from-initial-chunks-into-separate-css-output-file):

EDIT: It works if I add raw! to the list of loaders, unfortunately not with resolved requires within the css file.

```js
var webpack = require('webpack')
var ExtractTextPlugin = require("extract-text-webpack-plugin")

module.exports = {
    entry: './index.js',
    output: {
        path: './',
        filename: '[name].js',
        sourceMapFilename: "[name].js.map",
    },
    module: {
        preLoaders: [
            { test: /\.js$/, loader: 'source-map!imports?$=jquery' },
        ],
        loaders: [
            { test: /\.(jpe?g|png|gif|svg)$/i, loader: 'url?limit=8192'},
            { test: /\.html$/i, loader: 'html'},
            { test: /\.js$/, loader: 'babel', query: { presets: 'es2015' }},
            { test: /\.less$/, loader: ExtractTextPlugin.extract('style', 'css!less')},
        ]
    },
    plugins: [
        new ExtractTextPlugin("[name].css")
    ]
}
```

This is the stacktrace I get:

```js
Hash: 97193bb087c8626a9927
Version: webpack 1.13.2
Time: 5529ms
      Asset    Size  Chunks             Chunk Names
  bundle.js  257 kB       0  [emitted]  main
main.js.map  570 kB       0  [emitted]  main
    + 11 hidden modules

ERROR in ./css/main.less
Module build failed: TypeError: Cannot read property 'document' of undefined
    at arr (node_modules/css-loader/index.js!node_modules/less-loader/index.js!css/main.less:139:23)
    at Object.<anonymous> (node_modules/css-loader/index.js!node_modules/less-loader/index.js!css/main.less:140:4)
    at Object.<anonymous> (node_modules/css-loader/index.js!node_modules/less-loader/index.js!css/main.less:1695:31)
    at __webpack_require__ (node_modules/css-loader/index.js!node_modules/less-loader/index.js!css/main.less:21:30)
    at Object.module.exports._typeof (node_modules/css-loader/index.js!node_modules/less-loader/index.js!css/main.less:65:10)
    at __webpack_require__ (node_modules/css-loader/index.js!node_modules/less-loader/index.js!css/main.less:21:30)
    at Object.<anonymous> (node_modules/css-loader/index.js!node_modules/less-loader/index.js!css/main.less:48:29)
    at __webpack_require__ (node_modules/css-loader/index.js!node_modules/less-loader/index.js!css/main.less:21:30)
    at node_modules/css-loader/index.js!node_modules/less-loader/index.js!css/main.less:41:18
    at Object.<anonymous> (node_modules/css-loader/index.js!node_modules/less-loader/index.js!css/main.less:44:10)
    at Module._compile (module.js:556:32)
    at Object.exec (node_modules/webpack-core/lib/NormalModuleMixin.js:88:7)
    at Object.<anonymous> (node_modules/extract-text-webpack-plugin/loader.js:97:22)
    at Compiler.<anonymous> (node_modules/webpack/lib/Compiler.js:214:10)
    at node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (node_modules/extract-text-webpack-plugin/loader.js:78:5)
    at Compiler.next (node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.applyPluginsAsync (node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.applyPluginsAsync (node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.applyPluginsAsync (node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.seal (node_modules/webpack/lib/Compilation.js:525:7)
Child extract-text-webpack-plugin:
        + 4 hidden modules
```

Any help or feedback is very much appreciated!

**Comment by daniellecloss** [comment]
Did you try using the css-loader and less-loader?  Like this:
{ test: /\.less$/, loader: ExtractTextPlugin.extract('style-loader', 'css-loader!less-loader')},

instead of:
{ test: /\.less$/, loader: ExtractTextPlugin.extract('style', 'css!less')},

**Comment by scottdj92** [comment]
Closing due to age. If your issue persists, feel free to re-open.
