### ISSUE TITLE
Question: Is it possible to extract html using this plugin? How?

### ISSUE THREAD

**Issue by kabirbaidhya** [webpack-contrib/extract-text-webpack-plugin#355]
I'm wondering if it's possible to extract `html` content out of a bundle just the way wedo for css as shown in the example here https://webpack.js.org/guides/code-splitting-css/#in-the-plugin.

All the examples of `ExtractTextPlugin` I could find only shows how you can extract css. But I couldn't find any examples out there that explains extraction of html. 

**Is this possible with this plugin or not? Or does it support only css or sass/less?** 

I just tried it just using `raw-loader` and `html-loader` instead of `css-loader` but it didn't work for me.
```javascript
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
    entry: {
        app: './index.js'
    },
    resolve: {
        modules: [
            path.resolve('./src/app'),
            path.resolve('./node_modules')
        ]
    },
    output: {
        path: path.resolve(__dirname, './public/dist'),
        publicPath: '/dist/',
        filename: '[name].bundle.js',
        chunkFilename: '[id].[chunkhash].chunk.js'
    },
    module: {
        rules: [
            {
                test: /\.html$/,
                loader: ExtractTextPlugin.extract({
                    loader: 'html-loader',
                    fallbackLoader: 'raw-loader'
                })
            },
            {test: /\.js$/, loader: 'babel-loader'},
        ]
    },
    plugins: [
        new webpack.DefinePlugin({
            'process.env': {
                'NODE_ENV': JSON.stringify(process.env.NODE_ENV)
            }
        }),
        new webpack.optimize.CommonsChunkPlugin({
            name: 'common'
        }),
        new webpack.LoaderOptionsPlugin({
            debug: true
        }),
        new ExtractTextPlugin({filename: '[name].template.html', allChunks: true})
    ],
    devtool: 'source-map'
};
```

It throws error like this:
```
> webpack --watch --display-modules


Webpack is watching the files…

/home/kabir/ontarget/ontargetwebapi/node_modules/webpack/lib/Chunk.js:59
		throw new Error("Chunk.entry was removed. Use hasRuntime()");
		^

Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.get entry [as entry] (/home/kabir/ontarget/ontargetwebapi/node_modules/webpack/lib/Chunk.js:59:9)
    at /home/kabir/ontarget/ontargetwebapi/node_modules/extract-text-webpack-plugin/index.js:201:13
    at Array.filter (native)
    at Compilation.<anonymous> (/home/kabir/ontarget/ontargetwebapi/node_modules/extract-text-webpack-plugin/index.js:200:37)
    at Compilation.applyPlugins0 (/home/kabir/ontarget/ontargetwebapi/node_modules/tapable/lib/Tapable.js:68:14)
    at Compilation.seal (/home/kabir/ontarget/ontargetwebapi/node_modules/webpack/lib/Compilation.js:533:8)
    at /home/kabir/ontarget/ontargetwebapi/node_modules/webpack/lib/Compiler.js:474:16
    at /home/kabir/ontarget/ontargetwebapi/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/home/kabir/ontarget/ontargetwebapi/node_modules/webpack/lib/Compilation.js:452:11)
    at processModuleDependencies.err (/home/kabir/ontarget/ontargetwebapi/node_modules/webpack/lib/Compilation.js:423:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

I'm requiring my html templates like this: 
```javascript
import app from 'app/app';

app.directive('popover', function () {
    return {
        restrict: 'E',
        scope: {},
        template: require('./popover.html'),
        ...
    };
});

```
Is there any work around for making it work?

Note: I'm using Webpack 2 BTW

**Comment by michael-ciniawsky** [comment]
@kabirbaidhya Can you try with `raw-loader` in `options.loader` to get just the string of HTML?

**Comment by kabirbaidhya** [comment]
I've tried both of these:
```
{test: /\.html$/, loader: ExtractTextPlugin.extract({loader: 'raw-loader'})},
```
and
```
{test: /\.html$/, loader: ExtractTextPlugin.extract('raw-loader')}
```
Still no luck. Same error.

**Comment by michael-ciniawsky** [comment]
@kabirbaidhya https://github.com/jhnns/webpack-extract-index-html/blob/master/webpack.config.js (webpack v1)

This should definitely be possible, I will investigate 😛

**Comment by kabirbaidhya** [comment]
@michael-ciniawsky Tried that as well. Still same error :smile: 

```javascript
const extractHtml = new ExtractTextPlugin('template.html');
...
module: {
    rules: [
        {test: /\.html$/, loader: extractHtml.extract(['html-loader'])},
    ]
}
...
plugins: [
    extractHtml,
    ...
]
...
```

**Comment by bebraw** [comment]
Any update? You could get that error if you are running against webpack 1 or have old dependencies around. Could you set up a project to study?

**Comment by DanielJDufour** [comment]
I apologize if this isn't helpful, but I ran into the same error and fixed it by running `npm install -S extract-text-webpack-plugin`.  In my case, there was a node module that was requiring an old version.

**Comment by jasonwr** [comment]
@DanielJDufour I'm going to try extracting my html in the morning and will use the ExtractTextPlugin. Should work as is. Please note the version of Node you're running with.

**Comment by evilebottnawi** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions or not working. Example with `txt` files https://github.com/webpack-contrib/extract-text-webpack-plugin/tree/master/test/cases/simple .Thanks!
