### ISSUE TITLE
Webpack 2: You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by c-h-** [webpack-contrib/extract-text-webpack-plugin#398]
Please help me solve SCSS not compiling anymore.

Using latest version of all related plugins I cannot get scss to build.

Error:
```bash
ERROR in ./styles/main.scss
Module parse failed: C:\...\node_modules\extract-text-webpack-plugin\loader.js?{"omit":0,"remove":true,"fallback":"style-loader"}![object Object]![object Object]![object Object]!C:\...\src\styles\main.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import './variables';
|
| /**
 @ ./js/index.js 11:12-42
```

package.json
```json
{
    "sass-loader": "^5.0.1",
    "postcss-loader": "^1.2.2",
    "css-loader": "^0.26.1",
    "extract-text-webpack-plugin": "2.0.0-beta.3",
    "webpack": "^2.2.1",
}
```

webpack.config.js
```js
// CSS/SCSS
      {
        test: /\.(scss|css)$/,
        include: [
          path.resolve(__dirname, './src/styles'),
        ],
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          loader: [
            {
              loader: 'css-loader',
              options: {
                modules: true,
                importLoaders: 3,
                sourceMap: true,
              },
            }, {
              loader: 'postcss-loader',
              options: {
                browsers: 'last 2 version',
                sourceMap: true,
              },
            }, {
              loader: 'sass-loader',
              options: {
                // outputStyle: 'expanded',
                sourceMap: true,
                // sourceMapContents: true,
              },
            },
          ],
        }),
      },
```

Switching `loader` to `use` after `fallback` in ExtractTextPlugin options causes this error:
```bash
C:\...\node_modules\extract-text-webpack-plugin\index.js:133
        if(isString(loader) || !loader.query) return loader;
                                      ^

TypeError: Cannot read property 'query' of undefined
    at getLoaderWithQuery (C:\...\node_modules\extract-text-webpack-plugin\index.js:133:32)
    at Array.map (native)
    at Function.ExtractTextPlugin.extract (C:\...\node_modules\extract-text-webpack-plugin\index.js:200:4)
    at Object.<anonymous> (C:\...\webpack.config.js:80:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (C:\...\node_modules\webpack\bin\convert-argv.js:96:18)
    at C:\...\node_modules\webpack\bin\convert-argv.js:109:17
    at Array.forEach (native)
    at module.exports (C:\...\node_modules\webpack\bin\convert-argv.js:107:15)
    at Object.<anonymous> (C:\...\node_modules\webpack\bin\webpack.js:153:40)
```

Any tips? Thank you!

**Comment by bebraw** [comment]
I see you are using `"extract-text-webpack-plugin": "2.0.0-beta.3",`. It does not work with `use`. To get support for `use`, upgrade to the newest rc.

**Comment by michael-ciniawsky** [comment]
@c-h- Yep please update to `extract-text-webpack-plugin@2.0.0-rc.3` and also 

```diff
{
     loader: 'postcss-loader',
     options: {
-    browsers: 'last 2 version', // This options doesn't exisits in postcss-loader @see *
      sourceMap: true,
     }
}
```

### *

**postcss.config.js**
```js
modules.exports = (ctx) => ({
  plugins: [
      require('autoprefixer')({ browsers: 'last 2 versions' })
  ]
})
```

or

**webpack.config.js**
```diff
{
     loader: 'postcss-loader',
     options: {
+     plugins: () => [ require('autoprefixer')({ browsers: 'last 2 versions' }) ]
      sourceMap: true,
     }
}

```

**Comment by c-h-** [comment]
Awesome!!! thank you guys so much.
