### ISSUE TITLE
ERROR in Child compilation failed

### ISSUE THREAD

**Issue by jorawarsingh** [webpack-contrib/extract-text-webpack-plugin#420]
I am using the latest release candidate 3 and facing an issue when using this plugin. every works fine but but when i want to use styleUrls in my component i get this weired errors.

> ERROR in Child compilation failed:
> Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
>     at Object.module.exports.pitch (D:\lab\reactive-form-ng2\node_modules\extract-text-webpack-plugin\loader.js:27:9):
> Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example

I am trying to use aot plugin with webpack. is i remove styleUrls then it build as  is should.  Here is my small repo on [bitbucket.](https://bitbucket.org/jorawarsingh/modal-driven-form)
How to reproduce this.
 in src/app/app/app.component.ts uncomment the styleUrls and then build with npm run build and it will throw some errors including mentioned above but if you comment styleUrls line and build again it will success to build without any errors but then there will be no styles.

**Comment by scottdj92** [comment]
There's a PR up from the maintainer: [4189](https://github.com/webpack/webpack/pull/4189). When this is merged (should be within 1-2 days from now), this feature should work.

**Comment by priyasam** [comment]
Kindly let us know, when will this issue get resolved? I am also experiencing the same issue @2.0.0-rc.3

**Comment by ryanwilsonperkin** [comment]
@priyasam change has been merged, try pulling latest from webpack and testing out again

**Comment by deot** [comment]
you can try it,I solved the problem, but I was still very surprised
```js
// loader config for angular component styles 
{
  test: /\.(scss|css)$/,
  use: ['raw-loader','sass-loader'], // don't use css-loader for ng2 （unusual）
},
// loader config for global css files
{
  test: /\.scss$/,
  exclude: [/node_modules/, /src\/app/], 
  use: ExtractTextPlugin.extract({
    fallbackLoader: 'style-loader',
    use: ['css-loader','sass-loader']
  })
},
```

**Comment by patrikx3** [comment]
weird, i use the same settigns, but now the error is scss:
```bash
 ERROR in ./src/angular2/layout/cory-layout.scss
    Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
      at Object.module.exports.pitch (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder-angular2/node_modules/extract-text-webpack-plugin/loader.js:27:9)

```

**Comment by scottdj92** [comment]
@patrikx3 can you post your config? That error is usually thrown because an `ExtractTextPlugin` is not declared in the `plugins` array.

**Comment by patrikx3** [comment]
Pretty long though.
Thanks for looking at it.

```common.js```

```javascript
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

const root = require('corifeus-builder').config.root;
const folder = require('corifeus-builder/src/config/folder');

const nodeSassCssImporter = require('node-sass-css-importer');

const fileAsset = `name=assets/[name].[hash].[ext]`;

const ScriptExtHtmlWebpackPlugin = require('script-ext-html-webpack-plugin');

module.exports = (rootFolder = folder.src.root, env = 'dev') => {

    let compiler;
    if (env === 'production') {
        compiler =  {
            test: /\.ts$/,
            use: [
                {
                    loader: '@ngtools/webpack'
                }
            ]
        }
    } else {
        compiler =  {
            test: /\.ts$/,
            use: [
                {
                    loader: 'awesome-typescript-loader'
                }, {
                    loader: 'angular2-template-loader'
                }
            ]
        }
    }

    return {
        entry: {
            'bundle': `./${rootFolder}/angular2/boot.ts`,
        },

        //fixme this looks like for linked npm it needs
        resolve: {
            extensions: ['.ts', '.js', '.json'],
            modules: [root('src'), root('node_modules')]
        },

        module: {
            rules: [
                compiler,
                {
                    test: /\.json$/,
                    exclude: /node_modules/,
                    use: 'json-loader',
                    enforce: 'pre',
                },
                {
                    test: /\.html$/,
                    use: [{
                        loader : 'html-loader',
                        options: {
                            minimize: true,
                            caseSensitive: true
                        }
                    }]
                },
                {
                    test: /\.(png|jpe?g|gif|ico)$/,
                    use: `file-loader?${fileAsset}`
                },
                {
                    test: /\.css$/,
                    exclude: [
                        root(rootFolder, 'angular2'),
                    ],
//                    loader: ExtractTextPlugin.extract('style', 'css?sourceMap')
                    use: ExtractTextPlugin.extract(
                        {
                            fallback: 'style-loader',
                            use: 'css-loader'
                        }
                    )
                },
                {
                    test: /\.woff(\?v=\d+\.\d+\.\d+)?$/,
                    use: `url-loader?limit=10000&mimetype=application/font-woff&${fileAsset}`
                }, {
                    test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/,
                    use: `url-loader?limit=10000&mimetype=application/font-woff&${fileAsset}`
                }, {
                    test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
                    use: `url-loader?limit=10000&mimetype=application/octet-stream&${fileAsset}`
                }, {
                    test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
                    use: `file-loader?${fileAsset}`
                }, {
                    test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
                    use: `url-loader?limit=10000&mimetype=image/svg+xml&${fileAsset}`
                },
                {
                    test: /\.css$/,
                    include: [
                        root(rootFolder, 'angular2'),
                    ],
                    use: 'raw'
                },
                {
                    test: /\.scss$/,
                    exclude: /node_modules/,
                    use: ['raw-loader',
                        {
                            loader: 'sass-loader',
                            options: {
                                importer: nodeSassCssImporter({
                                    import_paths: []
                                })
                            }
                        }], // sass-loader not scss-loader
                }
            ]
        },
        plugins: [
            //fix some weird angular 2 error fix
            new webpack.ContextReplacementPlugin(
                // The (\\|\/) piece accounts for path separators in *nix and Windows
                /angular(\\|\/)core(\\|\/)(esm(\\|\/)src|src)(\\|\/)linker/,
                root(folder.build.browser.root), // location of your src
                { }
            ),

            new HtmlWebpackPlugin({
                template: `${rootFolder}/index.html`,
                inject: 'head'
            }),

            new ScriptExtHtmlWebpackPlugin({
                defaultAttribute: 'defer'
            })
        ]
    };
}
```

```prod.js```

```javascript
const webpack = require('webpack');
const webpackMerge = require('webpack-merge');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');

const root = require('corifeus-builder').config.root;
const folder = require('corifeus-builder/src/config/folder/index');

const ENV = process.env.NODE_ENV = process.env.ENV = 'production';

const AotPlugin = require('@ngtools/webpack').AotPlugin;


module.exports = (rootFolder = folder.src.root) => {
    const commonConfig = require('./common')(rootFolder, ENV);

    return webpackMerge(commonConfig, {
        devtool: 'source-map',

        output: {
            path: root(folder.build.browser.root),
            publicPath: '/',
            filename: '[name].[hash].js',
            chunkFilename: '[id].[hash].chunk.js'
        },

        plugins: [
            new AotPlugin({
                tsConfigPath: root('./tsconfig.json'),
                entryModule: 'src/angular2/application#Application'
            }),

            new webpack.DefinePlugin({
                'process.env': {
                    'ENV': JSON.stringify(ENV)
                }
            }),

            new webpack.optimize.CommonsChunkPlugin({
                name: ['bundle', /* 'vendor', 'polyfills' */],
                filename: '[name].[hash].js',
                minChunks: Infinity
            }),
            new webpack.optimize.UglifyJsPlugin({
                compress: {
                    warnings: false
                },
                // todo found out if mangle use or not
                mangle: true,
                sourceMap: false,
                comments: false,
                beautify: false
            }),
            new OptimizeCssAssetsPlugin(),
            new ExtractTextPlugin({
                filename: '[name].[hash].css',
                disable: false,
                allChunks: true
            }),
            new webpack.LoaderOptionsPlugin({
                debug: false
            }),

            new webpack.NoEmitOnErrorsPlugin(),

        ]
    })
}
```

**Comment by scottdj92** [comment]
You need to insantiate ExtractTextPlugin in your `plugins` array. adding `new ExtractTextPlugin({filename: 'bundle.css'})` should make it work

**Comment by patrikx3** [comment]
Ciao! 
How are you? :)))
I already have it:
```ts
new ExtractTextPlugin({
                filename: '[name].[hash].css',
                disable: false,
                allChunks: true
            }),
```

Still I cannot get it output.
Is it an AOT problem???
With simple JIT plus UglifyJS it works.
With AOT, it is missing my CSS, with no error.

**Comment by patrikx3** [comment]
it is in my prod.js
The common is some common info. I got the ExtractTextPlugin in my plugin. It is missing :(
Bruhuhuhuhu

**Comment by jorawarsingh** [comment]
After upgrading to latest the error is gone however there is still one error but that belong to @ngtools/webpack so i am closing this.
here is my confuguration 
```
{
       test: /\.css$/,
       include: path.resolve(process.cwd(), 'src', 'app'),
       use: ['to-string-loader', 'css-loader']
    },
    {
       test: /\.css$/,
       exclude: path.resolve(process.cwd(), 'src', 'app'),
       use: ExtractTextPlugin.extract({
            fallback: "style-loader",
            use: "css-loader"
        })
    }
```
and plugin 
`new ExtractTextPlugin('styles.css')`

 thanks for all help .... Regards

**Comment by Nikhil-04** [comment]
@jorawarsingh - "After upgrading to latest the error is gone" , what latest are you talking about here. Is it webpack latest version or extract-text-webpack-plugin version. Please clarify since I am confused. I am also getting the same issue in my project when i am trying to implement AOT which was JIT before to improve appllication loading time. Help will be deeply appreciated. TIA

**Comment by Kielan** [comment]
This thread doesn't actually have the answer anywhere or document or resolve this difficult to understand err response that many people seem to have at `new ExtractTextPlugin({` but still get this error.

**Comment by vixita-markana** [comment]
some times mistake in the path  template: path.join(__dirname, './src/index.html')  in webpack.js file
