### ISSUE TITLE
Error: data.filename should be a string

### ISSUE THREAD

**Issue by jedmao** [webpack-contrib/extract-text-webpack-plugin#437]
The [README states](https://github.com/webpack-contrib/extract-text-webpack-plugin#modify-filename) that `filename` could be a `Function`, so when I use a function like this:

```js
new ExtractTextPlugin({
    allChunks: true,
    filename: getPath => {
        return getPath('css/[name].css').replace('css/js', 'css');
    }
});
```

I don't expect an error like this:

```
[14:51:55] Requiring external module babel-core/register
Z:\project\node_modules\extract-text-webpack-plugin\schema\validator.js:11
                throw new Error(ajv.errorsText());
                ^

Error: data.filename should be string
    at validate (Z:\project\node_modules\extract-text-webpack-plugin\schema\validator.js:11:9)
    at new ExtractTextPlugin (Z:\project\node_modules\extract-text-webpack-plugin\index.js:125:3)
    at Object.<anonymous> (Z:/Documents/GitHub/halo/frunt/webpack.config.js:35:9)
    at Module._compile (module.js:571:32)
    at loader (Z:\project\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (Z:\project\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (Z:/Documents/GitHub/halo/frunt/gulpfile.babel.js:5:1)
    at Module._compile (module.js:571:32)
    at loader (Z:\project\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (Z:\project\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:488:32)
```

**Comment by ericnoguchi** [comment]
same issue here, 

according to  node_modules/extract-text-webpack-plugin/schema/plugin-schema.json
		
"filename": {
	"description": "The filename and path that ExtractTextPlugin will extract to",
	"type": "string"
},
 so ExtractTextPlugin fails validation its seems unless type is string.

**Comment by scottdj92** [comment]
@ericnoguchi @jedmao can you provide the version of extract-text that you're using? I can see that it passes validation in v2.0.0

**Comment by ericnoguchi** [comment]
@scottdj92  "extract-text-webpack-plugin": "2.0.0"

in **node_modules/extract-text-webpack-plugin/index.js:125** if I try to by bass validation as seen below I 
get another error TypeError: path.replace is not a function

```
function ExtractTextPlugin(options) {
	if (arguments.length > 1) {
		throw new Error("Breaking change: ExtractTextPlugin now only takes a single argument. Either an options " +
			"object *or* the name of the result file.\n" +
			"Example: if your old code looked like this:\n" +
			"    new ExtractTextPlugin('css/[name].css', { disable: false, allChunks: true })\n\n" +
			"You would change it to:\n" +
			"    new ExtractTextPlugin({ filename: 'css/[name].css', disable: false, allChunks: true })\n\n" +
			"The available options are:\n" +
			"    filename: string\n" +
			"    allChunks: boolean\n" +
			"    disable: boolean\n");
	}
	if (isString(options)) {
		options = { filename: options };
	} else {
		//schemaTester(pluginSchema, options); //  bypass validation
	}
	this.filename = options.filename;
	this.id = options.id != null ? options.id : ++nextId;
	this.options = {};
	mergeOptions(this.options, options);
	delete this.options.filename;
	delete this.options.id;
}
```

**Comment by scottdj92** [comment]
Can you provide a repo so I can take a look?

**Comment by ericnoguchi** [comment]
@scottdj92 

Sure checkout **extract-text-plugin** branch from the below repo

https://github.com/ericnoguchi/react-testing/

1. **npm install**
2. **npm run dev** and you will see the error

**Comment by valaxy** [comment]
Any hack I can do to fix this for now?

**Comment by giuseppepaul** [comment]
Any information about when this might be fixed? Or any kind of work around for the time being?

**Comment by scottdj92** [comment]
@ericnoguchi I've resolved your issue:

The issue is caused by v2.0.0 not having the latest validation code.

To resolve this add the github link to your `package.json`

`"extract-text-webpack-plugin": "git@github.com:webpack-contrib/extract-text-webpack-plugin.git",`

I'll make an issue [here](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/444).

Thanks for your help!

**Comment by ericnoguchi** [comment]
@scottdj92 

I am getting the following error when trying to install from git@github.com:webpack-contrib/extract-text-webpack-plugin.git


```
vagrant@MTL1-W-PC-02263-VDE:/var/www/projects/spartan-trueamateurs$ sudo npm install
npm ERR! git clone --template=/home/vagrant/.npm/_git-remotes/_templates --mirror ssh://git@github.com/webpack-contrib/extract-text-webpack-plugin.git /home/vagrant/.npm/_git-remotes/git-ssh-git-github-com-web
pack-contrib-extract-text-webpack-plugin-git-604c1167: Cloning into bare repository '/home/vagrant/.npm/_git-remotes/git-ssh-git-github-com-webpack-contrib-extract-text-webpack-plugin-git-604c1167'...
npm ERR! git clone --template=/home/vagrant/.npm/_git-remotes/_templates --mirror ssh://git@github.com/webpack-contrib/extract-text-webpack-plugin.git /home/vagrant/.npm/_git-remotes/git-ssh-git-github-com-web
pack-contrib-extract-text-webpack-plugin-git-604c1167: Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
npm ERR! git clone --template=/home/vagrant/.npm/_git-remotes/_templates --mirror ssh://git@github.com/webpack-contrib/extract-text-webpack-plugin.git /home/vagrant/.npm/_git-remotes/git-ssh-git-github-com-web
pack-contrib-extract-text-webpack-plugin-git-604c1167: Permission denied (publickey).
npm ERR! git clone --template=/home/vagrant/.npm/_git-remotes/_templates --mirror ssh://git@github.com/webpack-contrib/extract-text-webpack-plugin.git /home/vagrant/.npm/_git-remotes/git-ssh-git-github-com-web
pack-contrib-extract-text-webpack-plugin-git-604c1167: fatal: Could not read from remote repository.
npm ERR! git clone --template=/home/vagrant/.npm/_git-remotes/_templates --mirror ssh://git@github.com/webpack-contrib/extract-text-webpack-plugin.git /home/vagrant/.npm/_git-remotes/git-ssh-git-github-com-web
pack-contrib-extract-text-webpack-plugin-git-604c1167:
npm ERR! git clone --template=/home/vagrant/.npm/_git-remotes/_templates --mirror ssh://git@github.com/webpack-contrib/extract-text-webpack-plugin.git /home/vagrant/.npm/_git-remotes/git-ssh-git-github-com-web
pack-contrib-extract-text-webpack-plugin-git-604c1167: Please make sure you have the correct access rights
npm ERR! git clone --template=/home/vagrant/.npm/_git-remotes/_templates --mirror ssh://git@github.com/webpack-contrib/extract-text-webpack-plugin.git /home/vagrant/.npm/_git-remotes/git-ssh-git-github-com-web
pack-contrib-extract-text-webpack-plugin-git-604c1167: and the repository exists.
npm ERR! Linux 3.13.0-108-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/vagrant/.npm/_git-remotes/_templates --mirror ssh://git@github.com/webpack-contrib/extract-text-webpack-plugin.git /home/vagrant/.npm/_git-remotes/git-ssh-gi
t-github-com-webpack-contrib-extract-text-webpack-plugin-git-604c1167
npm ERR! Cloning into bare repository '/home/vagrant/.npm/_git-remotes/git-ssh-git-github-com-webpack-contrib-extract-text-webpack-plugin-git-604c1167'...
npm ERR! Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
```

**Comment by scottdj92** [comment]
Have you set up SSH with GitHub?

If not, use HTTPS: `https://github.com/webpack-contrib/extract-text-webpack-plugin.git`

**Comment by ericnoguchi** [comment]
@scottdj92  great! the issue is solved and filename as function works! saved me 50 lines of node code as I had to use fs to manually move all the css files to their correct location after build.

**Comment by jedmao** [comment]
Thanks! I'll revisit this later, but I trust that it's fixed now.
