### ISSUE TITLE
Error: EINVAL: invalid argument, uv_interface_addresses

### ISSUE THREAD

**Issue by joetidee** [webpack-contrib/extract-text-webpack-plugin#440]
After running npm build I get this (webpack v2.2.1 and extract-text-webpack-plugin v2.0.0):

```
clean-webpack-plugin: /mnt/c/ubuntu/au/client/dist has been removed.
Hash: df8e338a0fb08db0c189
Version: webpack 2.2.1
Time: 34883ms
                         Asset       Size  Chunks                    Chunk Names
   app.1471b79b2c9d3d2572b6.js    1.92 MB       0  [emitted]  [big]  main
app.1471b79b2c9d3d2572b6.js.gz     496 kB          [emitted]  [big]
                    index.html  784 bytes          [emitted]
   [0] ./~/react/react.js 56 bytes {0} [built]
 [446] ./client/src/app.jsx 19.1 kB {0} [built]
 [528] ./~/bootstrap/dist/js/bootstrap.js 69.7 kB {0} [built]
 [578] ./~/intl-locales-supported/index.js 925 bytes {0} [built]
 [594] ./~/jquery-ui-dist/jquery-ui.js 521 kB {0} [built]
 [826] ./client/src/helpers/loadTranslation.js 1.68 kB {0} [built]
 [834] ./client/src/routes.js 5.81 kB {0} [built]
 [836] ./~/react-intl/locale-data/en.js 7.15 kB {0} [built]
 [909] ./client/src/css/animate.css 1.43 kB {0} [built]
 [910] ./client/src/css/fonts.css 1.43 kB {0} [built]
 [912] ./client/src/fontello/css/animation.css 1.48 kB {0} [built]
 [913] ./client/src/fontello/css/fontello.css 1.48 kB {0} [built]
 [914] ./~/bootstrap/dist/css/bootstrap.css 1.27 kB {0} [built]
 [916] ./client/src/css/tidee-app.less 1.07 kB {0} [built]
 [928] multi ./client/src/app.jsx 28 bytes {0} [built]
    + 914 hidden modules

ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!./~/style-loader!./~/css-loader?{"minimize":true}!./~/bootstrap/dist/css/bootstrap.css
Module build failed: Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at Object.lib.networkInterfaces (/mnt/c/ubuntu/au/node_modules/macaddress/index.js:31:21)
    at Object.lib.one (/mnt/c/ubuntu/au/node_modules/macaddress/index.js:79:26)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/uniqid/index.js:15:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/postcss-filter-plugins/dist/index.js:9:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/cssnano/dist/index.js:21:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/css-loader/lib/processCss.js:16:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
 @ ./~/bootstrap/dist/css/bootstrap.css 4:14-200
 @ ./client/src/app.jsx
 @ multi ./client/src/app.jsx

ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!./~/style-loader!./~/css-loader?{"minimize":true}!./client/src/css/fonts.css
Module build failed: Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at Object.lib.networkInterfaces (/mnt/c/ubuntu/au/node_modules/macaddress/index.js:31:21)
    at Object.lib.one (/mnt/c/ubuntu/au/node_modules/macaddress/index.js:79:26)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/uniqid/index.js:15:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/postcss-filter-plugins/dist/index.js:9:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/cssnano/dist/index.js:21:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/css-loader/lib/processCss.js:16:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
 @ ./client/src/css/fonts.css 4:14-248
 @ ./client/src/app.jsx
 @ multi ./client/src/app.jsx

ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!./~/style-loader!./~/css-loader?{"minimize":true}!./client/src/css/animate.css
Module build failed: Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at Object.lib.networkInterfaces (/mnt/c/ubuntu/au/node_modules/macaddress/index.js:31:21)
    at Object.lib.one (/mnt/c/ubuntu/au/node_modules/macaddress/index.js:79:26)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/uniqid/index.js:15:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/postcss-filter-plugins/dist/index.js:9:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/cssnano/dist/index.js:21:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/css-loader/lib/processCss.js:16:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
 @ ./client/src/css/animate.css 4:14-250
 @ ./client/src/app.jsx
 @ multi ./client/src/app.jsx

ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!./~/style-loader!./~/css-loader?{"minimize":true}!./client/src/fontello/css/animation.css
Module build failed: Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at Object.lib.networkInterfaces (/mnt/c/ubuntu/au/node_modules/macaddress/index.js:31:21)
    at Object.lib.one (/mnt/c/ubuntu/au/node_modules/macaddress/index.js:79:26)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/uniqid/index.js:15:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/postcss-filter-plugins/dist/index.js:9:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/cssnano/dist/index.js:21:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/css-loader/lib/processCss.js:16:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
 @ ./client/src/fontello/css/animation.css 4:14-264
 @ ./client/src/app.jsx
 @ multi ./client/src/app.jsx

ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!./~/style-loader!./~/css-loader?{"minimize":true}!./client/src/fontello/css/fontello.css
Module build failed: Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at Object.lib.networkInterfaces (/mnt/c/ubuntu/au/node_modules/macaddress/index.js:31:21)
    at Object.lib.one (/mnt/c/ubuntu/au/node_modules/macaddress/index.js:79:26)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/uniqid/index.js:15:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/postcss-filter-plugins/dist/index.js:9:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/cssnano/dist/index.js:21:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/css-loader/lib/processCss.js:16:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
 @ ./client/src/fontello/css/fontello.css 4:14-263
 @ ./client/src/app.jsx
 @ multi ./client/src/app.jsx

ERROR in ./~/css-loader!./~/less-loader!./client/src/css/tidee-app.less
Module build failed: Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at Object.lib.networkInterfaces (/mnt/c/ubuntu/au/node_modules/macaddress/index.js:31:21)
    at Object.lib.one (/mnt/c/ubuntu/au/node_modules/macaddress/index.js:79:26)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/uniqid/index.js:15:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/postcss-filter-plugins/dist/index.js:9:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/cssnano/dist/index.js:21:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/css-loader/lib/processCss.js:16:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
 @ ./client/src/css/tidee-app.less 4:14-128
 @ ./client/src/app.jsx
 @ multi ./client/src/app.jsx

ERROR in ./~/css-loader!./~/less-loader!./client/src/css/login.less
Module build failed: Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at Object.lib.networkInterfaces (/mnt/c/ubuntu/au/node_modules/macaddress/index.js:31:21)
    at Object.lib.one (/mnt/c/ubuntu/au/node_modules/macaddress/index.js:79:26)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/uniqid/index.js:15:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/postcss-filter-plugins/dist/index.js:9:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/cssnano/dist/index.js:21:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/css-loader/lib/processCss.js:16:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
 @ ./client/src/css/login.less 4:14-124
 @ ./client/src/components/LoginForm.jsx
 @ ./client/src/containers/LoginPage.jsx
 @ ./client/src/routes.js
 @ ./client/src/app.jsx
 @ multi ./client/src/app.jsx

ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"id":1,"omit":1,"remove":true}!./~/style-loader!./~/css-loader?{"minimize":true}!./client/src/css/select2.css
Module build failed: Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at Object.lib.networkInterfaces (/mnt/c/ubuntu/au/node_modules/macaddress/index.js:31:21)
    at Object.lib.one (/mnt/c/ubuntu/au/node_modules/macaddress/index.js:79:26)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/uniqid/index.js:15:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/postcss-filter-plugins/dist/index.js:9:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/cssnano/dist/index.js:21:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/ubuntu/au/node_modules/css-loader/lib/processCss.js:16:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
 @ ./client/src/css/select2.css 4:14-250
 @ ./client/src/components/AuditTemplateListFilterModal.jsx
 @ ./client/src/containers/AuditTemplateListFilterModalContainer.jsx
 @ ./client/src/components/AuditTemplateList.jsx
 @ ./client/src/routes.js
 @ ./client/src/app.jsx
 @ multi ./client/src/app.jsx
Child html-webpack-plugin for "index.html":
       [0] ./~/lodash/lodash.js 540 kB {0} [built]
       [1] (webpack)/buildin/global.js 509 bytes {0} [built]
       [2] (webpack)/buildin/module.js 517 bytes {0} [built]
       [3] ./~/html-webpack-plugin/lib/loader.js!./~/html-webpack-template/index.ejs 6.74 kB {0} [built]
```

**Comment by scottdj92** [comment]
Can you post your webpack config?

**Comment by joetidee** [comment]
Here is my webpack config:

```
const path = require('path');
const merge = require("webpack-merge");
const webpack = require("webpack");
var nodeExternals = require('webpack-node-externals');

const TARGET = process.env.npm_lifecycle_event;
const PATHS = {
    app: path.join(__dirname, '/client/src/app.jsx'),
    build: path.join(__dirname, '/client/dist'),
    test: path.join(__dirname, '/client/tests')
};


const common = {
    entry: [
        PATHS.app
    ],
    output: {
        path: PATHS.build
    },
    module: {
        rules: [{
            test: /\.js?$/,
            use: ['babel-loader'],
            include: path.join(__dirname, '/shared')
        },{
            test: /\.jsx?$/,
            use: ['react-hot-loader','babel-loader?' + JSON.stringify({
                presets: ["es2015", "stage-0", "react"]
            })],
            include: path.join(__dirname, '/client/src')
        },{
            test: /\.less$/,
            use: ['style-loader', 'css-loader', 'less-loader']
        },
        {
            test: /\.ico$/,
            use: ["file-loader"]
        },
        {
            test: /\.png$/,
            use: ["url-loader?limit=100000"]
        },
        {
            test: /\.jpg$/,
            use: ["file-loader"]
        },
        {
            test: /\.(woff|woff2)(\?v=\d+\.\d+\.\d+)?$/,
            use: ["url-loader?limit=10000&mimetype=application/font-woff"]
        },
        {
            test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
            use: ["url-loader"]
        },
        {
            test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
            use: ["file-loader"]
        },
        {
            test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
            use: ["url-loader?limit=10000&mimetype=image/svg+xml"]
        },{
            test: /\.css$/,
            use: ['style-loader', 'css-loader']
        }]
    },
    plugins: [
        new webpack.ProvidePlugin({
            "$":"jquery",
            "jQuery":"jquery",
            'global.jQuery': 'jquery'
        }),
        new webpack.DefinePlugin({ 'typeof window': '\"object\"' })
    ],
    resolve: {
        extensions: ['.js', '.jsx', '.less', '.css'],
        alias: {
            'jquery-ui': 'jquery-ui-dist/jquery-ui.js'
        }
    }
};

// Default config.
if(TARGET === 'start' || TARGET){
    module.exports = merge(common, {
        devtool: 'eval-source-map',
        entry: [
            'eventsource-polyfill',
            'webpack-hot-middleware/client',
            'webpack/hot/only-dev-server',
            'babel-polyfill'
        ],
        output: {
            filename: 'app.js',
            publicPath: '/public/'
        },
        plugins: [
            new webpack.HotModuleReplacementPlugin(),
            new webpack.DefinePlugin({
                'process.env': {
                    'NODE_ENV': JSON.stringify('development')
                }
            })
        ],
        resolve: {
            modules: [
                path.resolve('./client/src'),
                "node_modules"
            ]
        },
        watch: true
    });
}

// Tests config.
if(TARGET === 'test' || TARGET === 'tdd' || TARGET === 'test-mocha'){
    module.exports = merge(common, {
        devtool: "cheap-module-source-map", // faster than 'source-map'
        externals: [
            nodeExternals(), // in order to ignore all modules in node_modules folder.
            {
                'react/addons': true,
                'react/lib/ExecutionEnvironment': true,
                'react/lib/ReactContext': true
            }
        ],
        output: {
            // sourcemap support for IntelliJ/Webstorm
            devtoolModuleFilenameTemplate: '[absolute-resource-path]',
            devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]'
        },
        resolve: {
            alias: {
                'app': PATHS.app
            }
        },
        module: {
            rules: [
                {
                    test: /\.js$/,
                    use: ["babel-loader"]
                },
                {
                    test: /\.jsx?$/,
                    use: ['babel-loader?cacheDirectory']
                }
            ]
        },
        target: 'node' // in order to ignore built-in modules like path, fs, etc.
    });
}

// Build config.
if(TARGET === 'build' || TARGET === 'stats'){
    var CompressionPlugin = require('compression-webpack-plugin');
    const HtmlWebpackPlugin = require('html-webpack-plugin');
    const CleanPlugin = require('clean-webpack-plugin');
    const ExtractTextPlugin = require('extract-text-webpack-plugin');
    const extractCSS = new ExtractTextPlugin('css/[name].css');
    const Visualizer = require('webpack-visualizer-plugin');
    //const pkg = require("./package.json");

    module.exports = merge(common, {
        entry: [
            /*vendor: Object.keys(pkg.dependencies).filter(function (v) {
             return v;
             }),*/
        ],
        module: {
            rules: [
                {
                    test: /\.css$/,
                    use: extractCSS.extract({
                        fallback: 'style-loader',
                        use: [
                            { loader: 'css-loader', options: { minimize: true } }
                        ]
                    })
                }
            ]
        },
        output: {
            filename: 'app.[chunkhash].js',
            /*filename: '[name].js',*/
            publicPath: 'http://auditor.tidee.com/public/'
        },
        plugins: [
            new webpack.DefinePlugin({
                'process.env': {
                    'NODE_ENV': JSON.stringify('production')
                }
            }),
            new webpack.optimize.UglifyJsPlugin(),
            /*new webpack.optimize.AggressiveMergingPlugin(), //Merge chunks*/
            new CompressionPlugin({
                asset: "[path].gz[query]",
                algorithm: "gzip",
                test: /\.js$|\.css$|\.html$/,
                threshold: 10240,
                minRatio: 0.8
            }),
            new HtmlWebpackPlugin({
                template: 'node_modules/html-webpack-template/index.ejs',
                title: 'Tidee',
                appMountId: 'app',
                inject: false
            }),
            new CleanPlugin(path.join(__dirname, '/client/dist')),
            new ExtractTextPlugin('[name].[chunkhash].css'),
            new Visualizer({
                filename: './statistics.html'
            })
        ],
        resolve: {
            modules: [
                path.resolve('./client/dist'),
                "node_modules"
            ]
        }
    });
}
```

**Comment by scottdj92** [comment]
What is `npm build` running?

**Comment by joetidee** [comment]
It's running the `common` section merged with the `TARGET === 'build'` section.

**Comment by scottdj92** [comment]
I mean the specific command. Like `webpack -p --env build`

**Comment by ekulabuhov** [comment]
Was it working before? What kind of changes did you do?

It looks like https://github.com/scravy/node-macaddress (that is used by uniq ID generator) is failing to retrieve your network interfaces. Could you try building a small example using that library alone and see if that works? (there's an example on their github page). 

Can you re-create the issue on a different machine? If not - the solution might be as simple as restarting your machine.

Also, please change the title of this issue to "Error: EINVAL: invalid argument, uv_interface_addresses".

**Comment by joetidee** [comment]
@scottdj92 the command within my package.json is:

`"build": "NODE_ENV=development webpack --config webpack.config.js -p"`

**Comment by joetidee** [comment]
I believe that this is an issue with Windows 10 Ubuntu. The solution is to ad the following to the top of your webpack.config.js file, until Microsoft release a proper fix:

```
try {
  require('os').networkInterfaces();
}
catch (e) {
  require('os').networkInterfaces = () => ({});
}
```

**Comment by khelmrab** [comment]
errors : (/mnt/c/ubuntu/au/node_modules/macaddress/index.js:31:21)
you have to replace iface line 31 in lib.networkInterfaces  with this
lib.networkInterfaces = function () {
var ifaces;
try {
ifaces=os.networkInterfaces();
} catch (e) {
ifaces=os.networkInterfaces = () => ({});
}
