### ISSUE TITLE
ReferenceError: self is not defined in Webpack 2

### ISSUE THREAD

**Issue by brickyang** [webpack-contrib/extract-text-webpack-plugin#453]
I am using webpack 2.2.1, extract-text-webpack-plugin 2.1.0 and CSS Modules. When I run `webpack -p --progress --colors` I got a pile of 

```
ERROR in ./container/style.css
Module build failed: ReferenceError: self is not defined

    at /Users/brick/code/contest/node_modules/style-loader/index.js!/Users/brick/code/contest/node_modules/css-loader/index.js?modules&localIdentName=[path][name]_[local]--[hash:base64:8]!/Users/brick/code/contest/node_modules/postcss-loader/index.js??ref--1-3!/Users/brick/code/contest/src/client/container/style.css:229:30
    at /Users/brick/code/contest/node_modules/style-loader/index.js!/Users/brick/code/contest/node_modules/css-loader/index.js?modules&localIdentName=[path][name]_[local]--[hash:base64:8]!/Users/brick/code/contest/node_modules/postcss-loader/index.js??ref--1-3!/Users/brick/code/contest/src/client/container/style.css:224:47
    at module.exports.module.exports (/Users/brick/code/contest/node_modules/style-loader/index.js!/Users/brick/code/contest/node_modules/css-loader/index.js?modules&localIdentName=[path][name]_[local]--[hash:base64:8]!/Users/brick/code/contest/node_modules/postcss-loader/index.js??ref--1-3!/Users/brick/code/contest/src/client/container/style.css:246:68)
    at Object.<anonymous> (/Users/brick/code/contest/node_modules/style-loader/index.js!/Users/brick/code/contest/node_modules/css-loader/index.js?modules&localIdentName=[path][name]_[local]--[hash:base64:8]!/Users/brick/code/contest/node_modules/postcss-loader/index.js??ref--1-3!/Users/brick/code/contest/src/client/container/style.css:474:36)
    at __webpack_require__ (/Users/brick/code/contest/node_modules/style-loader/index.js!/Users/brick/code/contest/node_modules/css-loader/index.js?modules&localIdentName=[path][name]_[local]--[hash:base64:8]!/Users/brick/code/contest/node_modules/postcss-loader/index.js??ref--1-3!/Users/brick/code/contest/src/client/container/style.css:21:30)
    at /Users/brick/code/contest/node_modules/style-loader/index.js!/Users/brick/code/contest/node_modules/css-loader/index.js?modules&localIdentName=[path][name]_[local]--[hash:base64:8]!/Users/brick/code/contest/node_modules/postcss-loader/index.js??ref--1-3!/Users/brick/code/contest/src/client/container/style.css:67:18
    at Object.<anonymous> (/Users/brick/code/contest/node_modules/style-loader/index.js!/Users/brick/code/contest/node_modules/css-loader/index.js?modules&localIdentName=[path][name]_[local]--[hash:base64:8]!/Users/brick/code/contest/node_modules/postcss-loader/index.js??ref--1-3!/Users/brick/code/contest/src/client/container/style.css:70:10)
    at Module._compile (module.js:571:32)
    at Object.exec (/Users/brick/code/contest/node_modules/webpack/lib/NormalModule.js:98:6)
    at Object.<anonymous> (/Users/brick/code/contest/node_modules/extract-text-webpack-plugin/loader.js:112:21)
    at Compiler.<anonymous> (/Users/brick/code/contest/node_modules/webpack/lib/Compiler.js:280:10)
    at /Users/brick/code/contest/node_modules/webpack/lib/Compiler.js:480:13
    at next (/Users/brick/code/contest/node_modules/tapable/lib/Tapable.js:138:11)
    at Compiler.<anonymous> (/Users/brick/code/contest/node_modules/extract-text-webpack-plugin/loader.js:93:4)
    at next (/Users/brick/code/contest/node_modules/tapable/lib/Tapable.js:140:14)
    at Compiler.<anonymous> (/Users/brick/code/contest/node_modules/webpack/lib/CachePlugin.js:62:5)
    at Compiler.applyPluginsAsyncSeries (/Users/brick/code/contest/node_modules/tapable/lib/Tapable.js:142:13)
    at /Users/brick/code/contest/node_modules/webpack/lib/Compiler.js:477:10
    at Compilation.applyPluginsAsyncSeries (/Users/brick/code/contest/node_modules/tapable/lib/Tapable.js:131:46)
    at self.applyPluginsAsync.err (/Users/brick/code/contest/node_modules/webpack/lib/Compilation.js:640:19)
    at Compilation.applyPluginsAsyncSeries (/Users/brick/code/contest/node_modules/tapable/lib/Tapable.js:131:46)
    at self.applyPluginsAsync.err (/Users/brick/code/contest/node_modules/webpack/lib/Compilation.js:631:11)
    at next (/Users/brick/code/contest/node_modules/tapable/lib/Tapable.js:138:11)
    at Compilation.compilation.plugin (/Users/brick/code/contest/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:140:5)
    at next (/Users/brick/code/contest/node_modules/tapable/lib/Tapable.js:140:14)
    at Compilation.compilation.plugin (/Users/brick/code/contest/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:140:5)
    at Compilation.applyPluginsAsyncSeries (/Users/brick/code/contest/node_modules/tapable/lib/Tapable.js:142:13)
    at self.applyPluginsAsync.err (/Users/brick/code/contest/node_modules/webpack/lib/Compilation.js:626:10)
    at Compilation.applyPluginsAsyncSeries (/Users/brick/code/contest/node_modules/tapable/lib/Tapable.js:131:46)
    at sealPart2 (/Users/brick/code/contest/node_modules/webpack/lib/Compilation.js:622:9)

ERROR in /Users/brick/code/contest/node_modules/extract-text-webpack-plugin/loader.js??ref--1-0!/Users/brick/code/contest/node_modules/style-loader/index.js!/Users/brick/code/contest/node_modules/css-loader/index.js?modules&localIdentName=[path][name]_[local]--[hash:base64:8]!/Users/brick/code/contest/node_modules/postcss-loader/index.js??ref--1-3!/Users/brick/code/contest/src/client/container/style.css doesn't export content
```
(this is only one of the errors)

My webpack config is

```
...
module: {
    rules: [
        {
            test: /\.jsx?$/,
            loader: 'babel-loader',
            exclude: /node_modules/
        },
       {
            test: /\.css$/,
            use: extractTextPlugin.extract({
                fallback: 'style-loader',
                use: [
                    'css-loader?modules&localIdentName=[path][name]_[local]--[hash:base64:8]',
                    {
                        loader: 'postcss-loader',
                        options: { plugins: () => [nested(), autoprefixer(), values] },
                    }
                ]
            }),
            exclude: [...]
        },
        {
            test: /\.css$/,
            use: extractTextPlugin.extract({
                fallback: 'style-loader',
                use: 'css-loader'
            }),
            include: [...],
        },
    ]
},
plugins: [
    new assetsPlugin({
        filename: 'assets.json',
        path: 'build'
    }),
    new extractTextPlugin({filename: '[name].[hash].css', ignoreOrder: true}),
    new webpack.optimize.UglifyJsPlugin({
        test: /(\.jsx|\.js)$/,
        minimize: true,
    })
],
...
```

It works fine if I remove extract-text-webpack-plugin.

**Comment by brickyang** [comment]
The problem is the `css-loader?modules&localIdentName=[path][name]_[local]--[hash:base64:8]`

I modified it to 

```
{
    test: /\.css$/,
    use: extractTextPlugin.extract({
        fallback: 'style-loader',
        use: [
            {
                loader: 'css-loader',
                options: {
                    modules: true,
                    localIdentName: '[path][name]_[local]--[hash:base64:8]',
                },
            },
            {
                loader: 'postcss-loader',
                options: { plugins: () => [ nested(), autoprefixer(), values] },
            }
        ]
    }),
    exclude: [...]
},
```
