### ISSUE TITLE
data['disabled'] should NOT have additional properties

### ISSUE THREAD

**Issue by cgonen** [webpack-contrib/extract-text-webpack-plugin#488]
Error: data['disabled'] should NOT have additional properties
I'm having this error running extract-text-webpack-plugin with webpack. How to fix it?

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\cgone\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@4.5.0
3 info using node@v7.9.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle pack3@1.0.0~predev: pack3@1.0.0
6 silly lifecycle pack3@1.0.0~predev: no script for predev, continuing
7 info lifecycle pack3@1.0.0~dev: pack3@1.0.0
8 verbose lifecycle pack3@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle pack3@1.0.0~dev: PATH: C:\Users\cgone\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Www\Projects\pack3\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;c:\Program Files\Intel\WiFi\bin\;c:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\cgone\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\cgone\AppData\Roaming\npm
10 verbose lifecycle pack3@1.0.0~dev: CWD: C:\Www\Projects\pack3
11 silly lifecycle pack3@1.0.0~dev: Args: [ '/d /s /c', 'webpack -d --watch' ]
12 silly lifecycle pack3@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle pack3@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: pack3@1.0.0 dev: `webpack -d --watch`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\cgone\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\cgone\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid pack3@1.0.0
16 verbose cwd C:\Www\Projects\pack3
17 verbose Windows_NT 10.0.14393
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\cgone\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 verbose node v7.9.0
20 verbose npm  v4.5.0
21 error code ELIFECYCLE
22 error errno 1
23 error pack3@1.0.0 dev: `webpack -d --watch`
23 error Exit status 1
24 error Failed at the pack3@1.0.0 dev script 'webpack -d --watch'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the pack3 package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     webpack -d --watch
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs pack3
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls pack3
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

and my webpack.config.js is:

```
var path = require('path');
var HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
    entry: './src/main.js',
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.min.js'
    },
    module: {
        rules: [{
            test: /\.scss$/,
            use: ExtractTextPlugin.extract({
                fallback: 'style-loader',
                use: ['css-loader', 'sass-loader'],
                publicPath: "/dist"
            })
        }]
    },
    plugins: [
        new HtmlWebpackPlugin({
            title: 'Custom template',
            minify: {
                  collapseWhitespace: true
            },
            hash: true,
            template: './src/template.html',
        }),
        new ExtractTextPlugin({
            filename: "style.css",
            disabled: false,
            allChunks: true
        })
    ]
}
```

Package.json versions:

```
"devDependencies": {
    "css-loader": "^0.28.0",
    "extract-text-webpack-plugin": "^2.1.0",
    "html-webpack-plugin": "^2.28.0",
    "node-sass": "^4.5.2",
    "sass-loader": "^6.0.3",
    "style-loader": "^0.16.1",
    "webpack": "^2.4.1"
  }
```
NPM -v // => 4.5.0
NODE -v => 7.9.0

**Comment by michael-ciniawsky** [comment]
@cgonen From a first glace this looks like a Options Validation Error, could you remove the `disable` from ETWP options?

**Comment by cgonen** [comment]
@michael-ciniawsky Thank you, that worked :-).

**Comment by cgonen** [comment]
@michael-ciniawsky Thank you, that worked 👍

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/master/schema/plugin-schema.json#L10

It's mispelled in your config `disabled => disable` and that's the reason why the options validator is complaining 😛
