### ISSUE TITLE
Less file not working

### ISSUE THREAD

**Issue by sjoshi2** [webpack-contrib/extract-text-webpack-plugin#510]
I am getting an "Error: Expected 'styles' to be an array of strings is being show in the browser. " And I can't figure out where I am going wrong. Can someone please help me out. Thanks in advance.

pakage.json includes these:
```javascript
"webpack": "~2.4.1",
"extract-text-webpack-plugin": "~2.1.0"
```
Below are are part of my webpack configs:
```javascript
const ExtractTextPlugin = require('extract-text-webpack-plugin');

// Create multiple instances
const extractCSS = new ExtractTextPlugin('styles.css');
const extractLESS = new ExtractTextPlugin('styles-two.css');

module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/,
        use: extractCSS.extract([ 'to-string-loader', 'css-loader' ])
      },
      {
        test: /\.less$/i,
       use: extractLESS.extract([ 'to-string-loader', 'css-loader', 'less-loader' ])
      },
    ]
  },
  plugins: [
    extractCSS,
    extractLESS
  ]
};
```

**Comment by michael-ciniawsky** [comment]
Please try without `to-string-loader`

**Comment by sjoshi2** [comment]
I tried without the to-string-loader and it still has the same error.

**Comment by michael-ciniawsky** [comment]
kk, please post the full `stacktrace`

**Comment by sjoshi2** [comment]
```javscript
Uncaught Error: Expected 'styles' to be an array of strings.
    at assertArrayOfStrings (http://localhost:3000/vendor.dll.js:47308:19)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://localhost:3000/vendor.dll.js:58159:13)
    at CompileMetadataResolver._getEntryComponentMetadata (http://localhost:3000/vendor.dll.js:58858:45)
    at http://localhost:3000/vendor.dll.js:58441:108
    at Array.map (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:3000/vendor.dll.js:58441:73)
    at JitCompiler._loadModules (http://localhost:3000/vendor.dll.js:69518:64)
    at JitCompiler._compileModuleAndComponents (http://localhost:3000/vendor.dll.js:69477:52)
    at JitCompiler.compileModuleAsync (http://localhost:3000/vendor.dll.js:69439:21)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:3000/vendor.dll.js:6134:25)
    at PlatformRef_.bootstrapModule (http://localhost:3000/vendor.dll.js:6120:21)
    at HTMLDocument.main (http://localhost:3000/main.bundle.js:115:10)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.dll.js:4113:31)
    at Zone.runTask (http://localhost:3000/polyfills.dll.js:3880:47)
    at HTMLDocument.ZoneTask.invoke (http://localhost:3000/polyfills.dll.js:4175:38)
```

**Comment by evilebottnawi** [comment]
@sjoshi2 seems your use `dll`, can your provide full configuration?

**Comment by sjoshi2** [comment]
Which config would you like me to post? 
I am using the https://github.com/AngularClass/angular-starter seed.

**Comment by evilebottnawi** [comment]
@sjoshi2 What can I do to reproduce the error? `angular-starter` works good for me, no errors.

**Comment by sjoshi2** [comment]
I have attached my project. I get the error in the browser when I am trying to run "npm start"
[PressRelease.zip](https://github.com/webpack-contrib/extract-text-webpack-plugin/files/1019283/PressRelease.zip)

**Comment by evilebottnawi** [comment]
@sjoshi2 thanks for repo, let's see what is wrong

**Comment by evilebottnawi** [comment]
@sjoshi2 seems your repo contain outdated deps, try to update their first.

**Comment by sjoshi2** [comment]
I was able to fix my issue using the below config. Thank you for all the help. 
```javascript     
       {
          test: /\.css$/,
          use: ['to-string-loader', 'css-loader'],
          exclude: [helpers.root('src', 'styles')]
        },
        {
          test: /\.less$/,
          use: ['to-string-loader'].concat(extractLESS.extract([ 'css-loader', 'less-loader' ])),
          exclude: [helpers.root('src', 'styles')]
        },
```
