### ISSUE TITLE
Error: chunk.sortModules is not a function webpack 3.3.0

### ISSUE THREAD

**Issue by tuananhzippy** [webpack-contrib/extract-text-webpack-plugin#581]
```
Unhandled rejection TypeError: chunk.sortModules is not a function
    at C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\extract-text-webpack-plugin\dist\index.js:188:19
    at C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\async\dist\async.js:3083:16
    at eachOfArrayLike (C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\async\dist\async.js:1003:9)
    at eachOf (C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\async\dist\async.js:1051:5)
    at Object.eachLimit (C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\async\dist\async.js:3145:5)
    at Compilation.<anonymous> (C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\extract-text-webpack-plugin\dist\index.js:184:27)
    at Compilation.applyPluginsAsyncSeries (C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\webpack\node_modules\tapable\lib\Tapable.js:142:13)
    at Compilation.seal (C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\webpack\lib\Compilation.js:580:8)
    at C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\webpack\lib\Compiler.js:510:16
    at C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\webpack\node_modules\tapable\lib\Tapable.js:225:11
    at C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\html-webpack-plugin\index.js:60:9
    at tryCatcher (C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Tuan Anh Zippy\Desktop\webpack\extract-text-webpack-plugin\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

**Comment by michael-ciniawsky** [comment]
Your `webpack.config.js` && `package.json` aswell please

**Comment by tuananhzippy** [comment]
My `webpack.config.js`

`var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextWebpackPlugin = require('extract-text-webpack-plugin');

module.exports = {
  entry: './app.js',
  output: {
    path: __dirname + '/dist',
    filename: 'bundle.js'
  },
  module: {
    rules: [
      {
        test: '/\.css$/',
        use: ExtractTextWebpackPlugin.extract({
          fallback: "style-loader",
          use: "css-loader"
        })
      }
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({
      title: 'Extract Text Webpack Plugin',
      filename: 'auto-generator.html',
      template: './index.html',
      minify: false
    }),
    new ExtractTextWebpackPlugin({
      filename: 'bundle.css',
      disable: false,
      allChunks: true
    })
  ],
  watch: true
}`

**Comment by michael-ciniawsky** [comment]
```diff
- test: '/\.css$/',
+ test: /\.css$/, // => no '' around Regex
```

If it doesn't wor, could you try without `watch` && with `{ filename: '[name].bundle.css' }`, the config looks ok so far, maybe a file where you `import css from './file.css'` could help

**Comment by tuananhzippy** [comment]
Thanks you, i tried but not yet.

**Comment by jmahc** [comment]
Shoot, mane.

I am catching the same issue! (using webpack@3.4.0).

Here is the sample repo: https://github.com/jmahc/that-react-app-you-want

Just run `yarn` then `yarn run build` which will throw the error!

```bash
ERROR in chunk manifest [entry]
[name].[chunkhash].js
Chunk.entry was removed. Use hasRuntime()
Error: Chunk.entry was removed. Use hasRuntime()
```

Headed to dinner, but hopefully this [package.json](https://raw.githubusercontent.com/jmahc/that-react-app-you-want/master/package.json/) link will suffice, as well as my [production build for webpack](https://raw.githubusercontent.com/jmahc/that-react-app-you-want/master/config/webpack.config.production.babel.js/).

**Comment by nchan0154** [comment]
@jmahc Thanks so much for that fix, it saved me and my team a whole evening of headaches!

**Comment by jmahc** [comment]
@nchan0154 No problem!  WD-40 works on code, too.

**Comment by nkbt** [comment]
We don't use manifest, and regexes are fine, but still have the same issue.

**Comment by michael-harvey** [comment]
Updating webpack to 3.4.1 solved this for me.

**Comment by jmahc** [comment]
@nkbt - Care to elaborate with your issue?

**Comment by d3viant0ne** [comment]
@nkbt - If you still have issues on `webpack@3.4.1` ping me so i can get this on the High Priority board.

**Comment by nkbt** [comment]
I will check `webpack@3.4.1`, hopefully it is gone. 

PS: my comment was mostly just a quick note so issue is not closed yet since we have some different case that failed.

**Comment by nkbt** [comment]
Works fine for us with `webpack@3.4.1` now, thanks!

**Comment by d3viant0ne** [comment]
So for anyone reading in the future, the Cliff notes version, `ChunkManifestPlugin` needs `webpack@3.4.1`.

Thanks to @michael-harvey / @jmahc & others for the testing :)

**Comment by gianmarcotoso** [comment]
I am having this issue with `webpack@3.4.1` and `extract-text-webpack-plugin@3.0.0`, but only when running webpack from node (running from CLI works fine).

```
const webpack = require('webpack')
const config = require('@client/webpack.config')
const compiler = webpack(config)

compiler.run((err, stats) => {
	console.log(stats)
})
```

Results in 

```
/Users/gianmarcotoso/Developer/experiments/ssr/src/client/node_modules/async/dist/async.js:1003
        iteratee(coll[index], index, onlyOnce(iteratorCallback));
        ^
TypeError: chunk.sortModules is not a function
    at /Users/gianmarcotoso/Developer/experiments/ssr/src/client/node_modules/extract-text-webpack-plugin/dist/index.js:188:19
    at /Users/gianmarcotoso/Developer/experiments/ssr/src/client/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/Users/gianmarcotoso/Developer/experiments/ssr/src/client/node_modules/async/dist/async.js:1003:9)
    at eachOf (/Users/gianmarcotoso/Developer/experiments/ssr/src/client/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/Users/gianmarcotoso/Developer/experiments/ssr/src/client/node_modules/async/dist/async.js:3145:5)
    at Compilation.<anonymous> (/Users/gianmarcotoso/Developer/experiments/ssr/src/client/node_modules/extract-text-webpack-plugin/dist/index.js:184:27)
    at Compilation.applyPluginsAsyncSeries (/Users/gianmarcotoso/Developer/experiments/ssr/node_modules/tapable/lib/Tapable.js:142:13)
    at Compilation.seal (/Users/gianmarcotoso/Developer/experiments/ssr/node_modules/webpack/lib/Compilation.js:579:8)
    at /Users/gianmarcotoso/Developer/experiments/ssr/node_modules/webpack/lib/Compiler.js:493:16
    at /Users/gianmarcotoso/Developer/experiments/ssr/node_modules/tapable/lib/Tapable.js:225:11
```

My `package.json`:

```
{
  "name": "client",
  "version": "1.0.0",
  "main": "dist/index.js",
  "license": "MIT",
  "scripts": {
    "build": "NODE_ENV=production webpack --progress -p --colors",
    "build:dev": "NODE_ENV=development webpack --progress --colors"
  },
  "dependencies": {
    "bootstrap": "^3.3.7",
    "react": "^15.6.1",
    "react-bootstrap": "^0.31.2",
    "react-dom": "^15.6.1"
  },
  "devDependencies": {
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "css-loader": "^0.28.4",
    "dotenv": "^4.0.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^0.11.2",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.6",
    "url-loader": "^0.5.9",
    "webpack": "^3.4.1",
    "webpack-dev-server": "^2.6.1"
  }
}
```

My `webpack.config.js`

```
require('dotenv').config()

const webpack = require('webpack')
const path = require('path')
const ExtractTextPlugin = require('extract-text-webpack-plugin')

const isProduction = process.env.NODE_ENV === 'production'

module.exports = {
	entry: {
		index: ['babel-polyfill', path.join(__dirname, 'src', 'index.js')]
	},
	output: {
		publicPath: '/',
		path: path.join(__dirname, 'dist'),
		filename: '[name].js'
	},
	module: {
		rules: [
			{ test: /\.jsx?$/, exclude: /node_modules/, use: ['babel-loader'] },
			{ test: /\.woff2?(\?v=\d+\.\d+\.\d+)?$/, loader: 'url-loader?limit=10000&mimetype=application/font-woff' },
			{ test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: 'url-loader?limit=10000&mimetype=application/octet-stream' },
			{ test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: 'file-loader' },
			{ test: /\.jpe?g(\?v=\d+\.\d+\.\d+)?$/, loader: 'file-loader' },
			{ test: /\.png(\?v=\d+\.\d+\.\d+)?$/, loader: 'file-loader' },
			{ test: /\.gif(\?v=\d+\.\d+\.\d+)?$/, loader: 'file-loader' },
			{ test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: 'url-loader?limit=10000&mimetype=image/svg+xml' },
			{
				test: /\.s?css$/,
				use: ExtractTextPlugin.extract('css-loader!sass-loader')
			}
		]
	},
	resolve: {
		extensions: ['.js', '.jsx', '.json', '.scss', '.css'],
			modules: ['node_modules'],
			alias: {
				'@client': path.join(__dirname, 'src'),
			}
	},
	plugins: [
		new ExtractTextPlugin({ filename: 'theme.css', allChunks: true  }),
		new webpack.DefinePlugin({
			'process.env': {
				NODE_ENV: JSON.stringify(process.env.NODE_ENV)
			},
			config: JSON.stringify(require('./env.js'))						
		})
	],
	devtool: isProduction ? false : 'eval-source-map',
	devServer: {
		port: process.env.DEVSERVER_PORT || 8082
	}
}
```

**Comment by webfelipemaia** [comment]
Thanks to @michael-harvey. 
My problem is solved, but in my case I had to install _bootstrap-sass_. Before reaching the solution I completely deleted the node_modules folder and installed it again. Then replaced _package.josn_ with [this content](https://github.com/laravel/laravel/blob/master/package.json) and I got here grateful.
