### ISSUE TITLE
webpack 2: Error when compiling having sass-loader errors

### ISSUE THREAD

**Issue by pakonawala** [webpack-contrib/extract-text-webpack-plugin#622]
Having issues with webpack 2 and extract-text-webpack-plugin it appears that the sass loader cant load the sass files any help will be greatly appriciated.

Config
var webpack = require('webpack');
const path = require('path');
var ExtractTextPlugin = require("extract-text-webpack-plugin");

// CSS files output
// They are outputed directly on the dist root folder because of the webpack resolve url loader. 
// CSS 'url()' are not processed correctly when the CSS files are in a subfolder (or I missed something there...)
var layoutsCssExtractTextPlugin = new ExtractTextPlugin("layouts.css");
var layoutsCssEditExtractTextPlugin = new ExtractTextPlugin("layouts-edit.css");
var portalCssExtractTextPlugin = new ExtractTextPlugin("portal.css");
var bootstrapCssExtractTextPlugin = new ExtractTextPlugin("bootstrap-iso.css");

const config = {

    entry: {
        app: "./main.ts", // The main entry point for the application.

        // Note that 'es6-promise' and 'whatwg-fetch' are necessary to get pnp work in IE
        // More info here https://github.com/OfficeDev/PnP-JS-Core/wiki/Install-and-Use
        vendor: [
            "jquery",
            "knockout",
            "knockout-mapping",
            "bootstrap/dist/js/bootstrap.min.js",
            "whatwg-fetch",
            "es6-promise",
            "react",
            "react-dom",
            "sp-pnp-js",
            "office-ui-fabric-react/lib/Panel",
            "office-ui-fabric-react/lib/Link",
            "office-ui-fabric-react/dist/css/fabric.min.css",
            "flickity/dist/flickity.min.css"
        ]
    },

    output: {
        filename: "js/app.js",
        path: path.join(__dirname, "dist"),

        // Expose the entry point as the 'Intranet' global var. 
        // We need this to be able to apply Knockout JS bindings manually for SharePoint display templates (the 'ko' variable is not exposed in the global context)
        library: ['Intranet']
    },

    node: {
        fs: "empty" // For the iCal feature (an error is raised otherwise)
    },

    // Context for entry point
    context: path.join(__dirname, "src"), 

    // Enable sourcemaps for debugging webpack's output.
    // To choose best source map mode: http://cheng.logdown.com/posts/2016/03/25/679045
    // Be careful, source maps are sometimes not recognized correctly by Google Chrome (use Google Chrome Canary if you encounter some troubles)
    devtool: "cheap-module-source-map",
    
    resolve: {                   
        extensions: [".webpack.js", ".web.js", ".js",".ts",".tsx"]        
    },

    module: {
        rules: [
            {
                // All output '.js' files will have any sourcemaps re-processed by 'source-map-loader'.
                test: /\.js$/,
                enforce: "pre",
                loader: "source-map-loader" 
            },
            {
                // We use the text loader to get the raw HTML markup for a Knockout component template file
                test: /\.html$/,
                use: 'text-loader'
            },
            {
                // Ouput images files directly into the 'dist' folder without modifications. They will be used by the CSS stylesheets.
                test: /\.(jpg|png|gif|ico)$/,
                use: [
                    {
                        loader: 'file-loader',
                        query : {
                            name: "./img/[name].[ext]"
                        }
                    }
                ],
            },
            {
                // Loader for TypeScript files (.ts)
                test: /\.tsx?$/,
                use: [
                    {
                        loader: 'ts-loader',
                        query : {
                            silent: true // To be able to run the webpack-bundle-size-analyzer without errors
                        }
                    }
                ],

                
            },
            {
                // CSS loader for the Office UI fabric styles
                test: /\.css$/,
                use: [
                    'style-loader',
                    'css-loader'
                ]
            },
            {
                // Custom fonts (Myriad Pro)
                test: /\.woff?$|\.woff2?$|\.ttf$|\.eot$|\.svg$/,
                use: [
                    {
                        loader: 'file-loader',
                        query : {
                            name: "./fonts/[name].[ext]"
                        }
                    }
                ],
               
            },
            {
                // Sass Loader. Note that we use the resolve-url loader to insert relative path to images into style sheets
                test: /\.scss$/,
                use: portalCssExtractTextPlugin.extract({
                        fallback: 'style-loader',
                        use: [
                            {
                                loader: 'css-loader',
                            },
                            {
                                loader: 'resolve-url-loader'
                            },
                            {
                                loader: "sass-loader",
                                options: {
                                    sourceMap: true
                                }
                            }
                        ],
                }),
                exclude: /(layouts|layouts-edit)\.scss$/
            },
            {
                // Page layouts styles (display and edit) are bundled separately. The loading is controlled by the page layout itself. 
                test: /layouts\.scss$/,
                use: layoutsCssExtractTextPlugin.extract({
                        fallback: 'style-loader',
                        use: [
                            {
                                loader: 'css-loader',
                            },
                            {
                                loader: "sass-loader",
                                options: {
                                    sourceMap: true
                                }
                            }
                        ],
                }),
            },  
            {
                test: /layouts-edit\.scss$/,
                use: layoutsCssEditExtractTextPlugin.extract({
                        fallback: 'style-loader',
                        use: [
                            {
                                loader: 'css-loader',
                            },
                            {
                                loader: "sass-loader",
                                options: {
                                    sourceMap: true
                                }
                            }
                        ],
                }),
            },  
            {
                // Isolate the Bootstrap CSS to avoid conflicts with the SharePoint default CSS
                // More info here: https://formden.com/blog/isolate-bootstrap
                // We used a customized CSS version of Bootstrap (http://getbootstrap.com/customize/) because we don't need the full package
                test: /\.less$/,
                use: bootstrapCssExtractTextPlugin.extract({
                        fallback: 'style-loader',
                        use: [
                            {
                                loader: 'css-loader',
                                options: {
                                    sourceMap: true
                                }
                            },
                            {
                                loader: "string-replace-loader",
                                query: {
                                    multiple: [
                                        { search: '\.bootstrap-iso body', replace: '.bootstrap-iso' },
                                        { search: '\.bootstrap-iso html', replace: 'bootstrap-iso' }
                                    ]
                                }
                            },
                            {
                                loader: 'less-loader'
                            },                            
                        ],
                }),                
            }, 
        ]
    },

    plugins: [

        // Every time webpack encounters $, jQuery, window.jQuery or ko, it will replace it by the correct library dependency
        // Especially useful for the default bootstrap.min.js file
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            "window.jQuery" : 'jquery',
            ko : 'knockout'
        }),

        portalCssExtractTextPlugin,
        bootstrapCssExtractTextPlugin,
        layoutsCssExtractTextPlugin,
        layoutsCssEditExtractTextPlugin,

        // Split the application into chunks
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            filename: 'js/vendor.js',
        }),

        // Load only the needed locales to reduce the size of the bundle
        new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /en|fr/)
    ]
};

module.exports = config;

Error I Get
ERROR in C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\extract-text-webpack-plugin\loader.js??ref--8-0!C:\Users\vincent.nawala\Documents\Office 365\W
eb Part\Homepage\app\node_modules\style-loader\index.js!C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\css-loader\index.js!C:\Users\vincent.nawala\Doc
uments\Office 365\Web Part\Homepage\app\node_modules\sass-loader\lib\loader.js??ref--8-3!C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\src\styles\css\layouts-edit
.scss doesn't export content
Child extract-text-webpack-plugin:
       [0] ../~/css-loader!../~/resolve-url-loader!../~/sass-loader/lib/loader.js?{"sourceMap":true}!./styles/css/global.scss 3.06 kB {0} [built] [failed] [1 error]

    ERROR in ../~/css-loader!../~/resolve-url-loader!../~/sass-loader/lib/loader.js?{"sourceMap":true}!./styles/css/global.scss
    Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\vendor'
        at Error (native)
        at Object.fs.readdirSync (fs.js:951:18)
        at Object.getInstalledBinaries (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\extensions.js:123:13)
        at foundBinariesList (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\errors.js:20:15)
        at foundBinaries (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\errors.js:15:5)
        at Object.module.exports.missingBinary (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\errors.js:45:5)
        at module.exports (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\binding.js:15:30)
        at Object.<anonymous> (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\index.js:14:35)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\sass-loader\lib\loader.js:3:14)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at loadLoader (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\loadLoader.js:13:17)
        at iteratePitchingLoaders (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at iteratePitchingLoaders (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
        at C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\LoaderRunner.js:173:18
        at loadLoader (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\loadLoader.js:36:3)
        at iteratePitchingLoaders (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at iteratePitchingLoaders (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\LoaderRunner.js:165:10)

**Comment by evilebottnawi** [comment]
@pakonawala Seems you have invalide configuration `sass-loader`. Can you create minimum reproducible test repo?

**Comment by evilebottnawi** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!
