### ISSUE TITLE
webpack3.3.0 extract-text-webpack-plugin3.0.0, Error executing webpack command 

### ISSUE THREAD

**Issue by qingyulove** [webpack-contrib/extract-text-webpack-plugin#624]
### `Config`
---

**webpack.config.js**
```js
var webpack = require('webpack');
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var config = {
     entry: {
        'common' : ['./src/page/commons/index.js'],
     	'index' : ['./src/page/index/index.js'],
     	'login' : ['./src/page/login/index.js']
     },
     output: {
         path: './dist',
         filename: 'js/[name].js'
     },
     externals : {
     	'jquery' : 'window.jQuery'
     },
      module: {
        rules: [
          {
            test: /\.css$/,
            use: ExtractTextPlugin.extract({
              fallback: "style-loader",
              use: "css-loader"
            })
          }
        ]
      },
     plugins : [
        new webpack.optimize.CommonsChunkPlugin({
            name : 'common',
            filename : 'js/base.js'
        }),
        new ExtractTextPlugin("styles.css"),
     ]
 }

 module.exports = config
```

### `Logs`
---

```bash
.../node_modules/extract-text-webpack-plugin/dist/lib/helpers.js:15
  
return chunk.isInitial() || chunk.parents.length === 0;
              ^
```

```
TypeError: chunk.isInitial is not a function
    at isInitialOrHasNoParents (/Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/extract-text-webpack-plugin/dist/lib/helpers.js:15:16)
    at /Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/extract-text-webpack-plugin/dist/index.js:187:94
    at /Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1003:9)
    at eachOf (/Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3145:5)
    at Compilation.<anonymous> (/Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/extract-text-webpack-plugin/dist/index.js:184:27)
    at Compilation.applyPluginsAsync (/Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.seal (/Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/webpack/lib/Compilation.js:525:7)
    at Compiler.<anonymous> (/Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/webpack/lib/Compilation.js:445:10)
    at /Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/webpack/lib/Compilation.js:417:12
    at /Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/async/lib/async.js:52:16
    at done (/Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/async/lib/async.js:246:17)
    at /Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/async/lib/async.js:44:16
    at /Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/async/lib/async.js:52:16
    at done (/Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/async/lib/async.js:246:17)
    at /Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/async/lib/async.js:44:16
    at /Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (/Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/webpack/lib/Compilation.js:185:8)
    at Compilation.processModuleDependencies (/Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/webpack/lib/Compilation.js:170:7)
    at /Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/webpack/lib/Compilation.js:320:12
    at /Users/wqy/Documents/workspace/mmall/mmall-fe/node_modules/webpack/lib/Compilation.js:123:4
    at Array.forEach (native)
```

> edited by @michael-ciniawsky (Formatting)

**Comment by michael-ciniawsky** [comment]
Could you try

**webpack.config.js**
```js
plugins : [
  new CommonsChunkPlugin({
    name: [ 'vendor' ],
    minChunks: Infinity
  }),
  new ExtractTextPlugin({
   filename: '[name].css',
   allChunks: true,
   // ignoreOrder: true
  })
]
```

**Comment by qingyulove** [comment]
Thank you for your advice, I convert webpack to 3.5.6 version of the run is good, then I went back to the version of webpack3.3.0 running good, before the problem is now unable to reproduce, I am sorry that I can't try your suggestion. I'll try again when the problem is repeated. Thank you very much for your advice

**Comment by michael-ciniawsky** [comment]
Feel free to reopen if still regressions
