### ISSUE TITLE
Angular4 : ERROR in Error: Child compilation failed: Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin | in Angular 4

### ISSUE THREAD

**Issue by shurvirmori** [webpack-contrib/extract-text-webpack-plugin#646]
:heavy_exclamation_mark: When I am trying to build my Angular 4 App, with command `ng build --prod` , this error throws. :bowtie: :heavy_exclamation_mark:

`ERROR in Error: Child compilation failed: Module build failed: 
Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, 
refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
at Object.pitch (D:\Project\demo\node_modules\@angular\cli\node_modules\extract-text-webpack-plugin\dist\loade
r.js:53:11):
Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpac
k/extract-text-webpack-plugin for the usage example
    at childCompiler.runAsChild (D:\Project\demo\node_modules\@ngtools\webpack\src\resource_loader.js:44:28)
    at compile (D:\Project\demo\node_modules\webpack\lib\Compiler.js:304:11)
    at applyPluginsAsync.err (D:\Project\demo\node_modules\webpack\lib\Compiler.js:520:14)
    at next (D:\Project\demo\node_modules\tapable\lib\Tapable.js:202:11)
    at Compiler.<anonymous> (D:\Project\demo\node_modules\webpack\lib\CachePlugin.js:62:5)
    at Compiler.applyPluginsAsyncSeries (D:\Project\demo\node_modules\tapable\lib\Tapable.js:206:13)
    at compilation.seal.err (D:\Project\demo\node_modules\webpack\lib\Compiler.js:517:11)
    at next (D:\Project\demo\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.compilation.plugin (D:\Project\demo\node_modules\@angular\cli\plugins\suppress-entry-chunks-web
pack-plugin.js:38:17)
    at Compilation.applyPluginsAsyncSeries (D:\Project\demo\node_modules\tapable\lib\Tapable.js:206:13)
    at self.applyPluginsAsync.err (D:\Project\demo\node_modules\webpack\lib\Compilation.js:671:19)
    at Compilation.applyPluginsAsyncSeries (D:\Project\demo\node_modules\tapable\lib\Tapable.js:195:46)
    at self.applyPluginsAsync.err (D:\Project\demo\node_modules\webpack\lib\Compilation.js:662:11)
    at next (D:\Project\demo\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.<anonymous> (D:\Project\demo\node_modules\uglifyjs-webpack-plugin\dist\index.js:244:6)
    at Compilation.applyPluginsAsyncSeries (D:\Project\demo\node_modules\tapable\lib\Tapable.js:206:13)
    at self.applyPluginsAsync.err (D:\Project\demo\node_modules\webpack\lib\Compilation.js:657:10)
    at Compilation.applyPluginsAsyncSeries (D:\Project\demo\node_modules\tapable\lib\Tapable.js:195:46)
    at sealPart2 (D:\Project\demo\node_modules\webpack\lib\Compilation.js:653:9)
    at Compilation.applyPluginsAsyncSeries (D:\Project\demo\node_modules\tapable\lib\Tapable.js:195:46)
    at Compilation.seal (D:\Project\demo\node_modules\webpack\lib\Compilation.js:596:8)
    at applyPluginsParallel.err (D:\Project\demo\node_modules\webpack\lib\Compiler.js:514:17)`

My Angular CLI Version is : **1.4.3**
My Angular npm version is : **5.4.2**
My Angular node version is : **v6.11.2**
I had tried so many things, but not found proper solution regarding this.:runner:
:bow:Please help me to solve this.:bow:

**Comment by d3viant0ne** [comment]
You will have to take this up with the angular/cli group.

**Comment by shurvirmori** [comment]
if it is angular/cli group , then why error shows 
`Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin` ?

**Comment by d3viant0ne** [comment]
The angular/cli does not expose it's webpack configuration & this is a configuration problem which means one of two things.

1.) There is an issue in the version of the CLI you are using & you should upgrade.

 - If the issue still exists, you are doing something outside the norm in your application.

2.) You ejected & have a configuration problem.

In either case, the tooling / configuration behind the Angular CLI is extensively tested & a configuration issue in the base CLI would be extremely wide spread. Whatever the issue is, it's related to something you are doing within you angular application.
