### ISSUE TITLE
TypeError while running the webpack build 'Cannot call a class as a function' cause by extract-text-webpack-plugin

### ISSUE THREAD

**Issue by vojtamares** [webpack-contrib/extract-text-webpack-plugin#659]
Hello,

as the title says, I am having a trouble with calling the plugin's index.js, in webpack.config.js I tried all the syntax I know from different languages (I am not JS dev so...), like `new extractCSS(), new extractSASS()`. But I couldn't figure it out. Idk if it is a bug or my missunderstanding of something...

Here is error message from terminal:
```
Vojta-Mac:ddm_web vojta$ npm run build

> ddm-hp.cz@0.2.0 build /Users/vojta/Documents/DDM/ddm_web
> webpack

/Users/vojta/Documents/DDM/ddm_web/node_modules/extract-text-webpack-plugin/dist/index.js:47
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
                                                                                            ^

TypeError: Cannot call a class as a function
    at _classCallCheck (/Users/vojta/Documents/DDM/ddm_web/node_modules/extract-text-webpack-plugin/dist/index.js:47:99)
    at ExtractTextPlugin (/Users/vojta/Documents/DDM/ddm_web/node_modules/extract-text-webpack-plugin/dist/index.js:55:5)
    at Object.<anonymous> (/Users/vojta/Documents/DDM/ddm_web/webpack.config.js:6:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ddm-hp.cz@0.2.0 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ddm-hp.cz@0.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vojta/.npm/_logs/2017-11-02T06_44_56_188Z-debug.log
```

Here is my webpack.config.js:
```javascript
const path = require('path');
const manifest = require('webpack-manifest-plugin');
const webpack = require('webpack');
const extractTextPlugin = require('extract-text-webpack-plugin');

const extractCSS = extractTextPlugin('css/[name]-static.css');
const extractSASS = extractTextPlugin('css/[name].css');

module.exports = {
    entry: './src/entry.js',
    output: {
        filename: '[name].[chunkhash].js',
        path: path.resolve(__dirname, 'www/dist')
    },
    module: {
        rules: [
            {
                test: /\.css$/,
                use: extractCSS.extract([ 'css-loader', 'autoprefixer', 'postcss-loader' ])
            },
            {
                test: /\.scss$/i,
                use: extractSASS.extract([ 'css-loader', 'autoprefixer', 'sass-loader' ])
            },
        ]
    },
    plugins: [
        new manifest(),
        new webpack.ProvidePlugin({
            'window.Nette': 'nette-forms',
            $: 'jquery',
            jQuery: 'jquery',
            'window.jQuery': 'jquery',
            Popper: ['popper.js', 'default']
        }),
        new extractCSS(),
        new extractSASS()
    ]
};
```

I am using webpack 3.8.1 and extract-text plugin 3.0.2 versions.

The command `npm run build` is technically `npm run webpack`...

Thank you for any help!

**Comment by michael-ciniawsky** [comment]
```js
// create Instances with new and assign them
const extractCSS = new ExtractTextPlugin('css/[name]-static.css');
const extractSASS =  new ExtractTextPlugin('css/[name].css');

...
{
  plugins: [
     // use Instances
     extractCSS(),
     extractSASS()
  ]
}
```
