### ISSUE TITLE
chunk.sortModules() is not a function.

### ISSUE THREAD

**Issue by DamnedScholar** [webpack-contrib/extract-text-webpack-plugin#695]
I just installed this plugin yesterday (release `3.0.2`) and it immediately broke the compile process.

```
λ npm run dev

> arc@0.1.0 dev D:\github\holocron\holocron-web
> npm run env:dev -- webpack-dev-server


> arc@0.1.0 env:dev D:\github\holocron\holocron-web
> cross-env NODE_ENV=development "webpack-dev-server"

Happy[jsx-1b1e1e7e]: Version: 3.1.0. Using cache? Yes. Threads: 8 (shared pool)
Project is running at http://0.0.0.0:3000/
webpack output is served from /
Content not from webpack is served from public
404s will fallback to /
Happy[jsx-1b1e1e7e]: Loaded 872 entries from cache. (0 were stale)
Happy[jsx-1b1e1e7e]: All set; signaling webpack to proceed.
 78% advanced chunk optimizationD:\github\holocron\holocron-web\node_modules\extract-text-webpack-plugin\dist\index.js:188
            chunk.sortModules();
                  ^

TypeError: chunk.sortModules is not a function
    at D:\github\holocron\holocron-web\node_modules\extract-text-webpack-plugin\dist\index.js:188:19
    at D:\github\holocron\holocron-web\node_modules\async\dist\async.js:3096:16
    at eachOfArrayLike (D:\github\holocron\holocron-web\node_modules\async\dist\async.js:1055:9)
    at eachOf (D:\github\holocron\holocron-web\node_modules\async\dist\async.js:1103:5)
    at Object.eachLimit (D:\github\holocron\holocron-web\node_modules\async\dist\async.js:3158:5)
    at Compilation.<anonymous> (D:\github\holocron\holocron-web\node_modules\extract-text-webpack-plugin\dist\index.js:184:27)
    at Compilation.applyPluginsAsyncSeries (D:\github\holocron\holocron-web\node_modules\tapable\lib\Tapable.js:206:13)
    at Compilation.seal (D:\github\holocron\holocron-web\node_modules\webpack\lib\Compilation.js:579:8)
    at D:\github\holocron\holocron-web\node_modules\webpack\lib\Compiler.js:493:16
    at D:\github\holocron\holocron-web\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\github\holocron\holocron-web\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (D:\github\holocron\holocron-web\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by michael-ciniawsky** [comment]
Please provide more info about your setup, does it work without `happypack`, which version of `webpack` are you using etc ?

**Comment by DamnedScholar** [comment]
I'm using `2.6.0`. Disabling `happypack` actually fixes the whole issue for me and Webpack compiles successfully with the `ExtractTextPlugin` code uncommented.

**Comment by michael-ciniawsky** [comment]
It's generally better to use `webpack` v3.0.0 with ETWP `v3.0.0` :). I can't tell you exactly where and why `happypack` fails, but it needs to stringify all `options` etc which maybe failing with webpack API (`webpack >= v2.0.0`) and the EWTP Code is already quite complex without any guarantee to work in parallel etc etc. In short I personally won't use/recommend `happypack` anymore with `webpack >= v2.0.0`.  Use the [`cache-loader`](https://guthub.com/webpack-contrib/cache-loader) to reduce build times instead
