### ISSUE TITLE
TypeError: extractedChunk.forEachModule is not a function

### ISSUE THREAD

**Issue by ulivz** [webpack-contrib/extract-text-webpack-plugin#706]
- Webpack Version: 3.10.0
- Version: 3.0.2
- Error Stack:

```
/Users/haolchen/Documents/__self__/v-codemirror/node_modules/extract-text-webpack-plugin/dist/index.js:240
                extractedChunk.forEachModule(function (module) {
                               ^

TypeError: extractedChunk.forEachModule is not a function
    at /Users/haolchen/Documents/__self__/v-codemirror/node_modules/extract-text-webpack-plugin/dist/index.js:240:32
    at Array.forEach (native)
    at /Users/haolchen/Documents/__self__/v-codemirror/node_modules/extract-text-webpack-plugin/dist/index.js:238:29
    at /Users/haolchen/Documents/__self__/v-codemirror/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/haolchen/Documents/__self__/v-codemirror/node_modules/async/dist/async.js:998:13)
    at /Users/haolchen/Documents/__self__/v-codemirror/node_modules/async/dist/async.js:906:16
    at /Users/haolchen/Documents/__self__/v-codemirror/node_modules/extract-text-webpack-plugin/dist/index.js:229:15
    at /Users/haolchen/Documents/__self__/v-codemirror/node_modules/async/dist/async.js:421:16
    at eachOfArrayLike (/Users/haolchen/Documents/__self__/v-codemirror/node_modules/async/dist/async.js:991:9)
    at eachOf (/Users/haolchen/Documents/__self__/v-codemirror/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/Users/haolchen/Documents/__self__/v-codemirror/node_modules/async/dist/async.js:3145:5)
    at /Users/haolchen/Documents/__self__/v-codemirror/node_modules/extract-text-webpack-plugin/dist/index.js:191:29
    at /Users/haolchen/Documents/__self__/v-codemirror/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/Users/haolchen/Documents/__self__/v-codemirror/node_modules/async/dist/async.js:1003:9)
    at eachOf (/Users/haolchen/Documents/__self__/v-codemirror/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/Users/haolchen/Documents/__self__/v-codemirror/node_modules/async/dist/async.js:3145:5)
```

**Comment by evilebottnawi** [comment]
@ulivz seems you use `webpack@2` with new version plugin. Look https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/cc3ba946ef4066264410737ce5bd43d0c7d724f1/CHANGELOG.md#300-rc0-2017-07-07
