### ISSUE TITLE
Using styleUrls instead of importing css file causes error

### ISSUE THREAD

**Issue by JonWallsten** [webpack-contrib/extract-text-webpack-plugin#734]
I noticed back in last fall when trying to get Angular 5 to work with this plugin that when using styleUrls instead of importing the css file, I get the following error: 

```
Error: Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract
-text-webpack-plugin for the usage example
    at Object.pitch (C:\repo\web-app-angular\node_modules\extract-text-webpack-plugin\dist\loader.js:59:11)
    at Object.<anonymous> (C:\repo\web-app-angular\src\app\app.component.css:76:7)
    at __webpack_require__ (C:\repo\web-app-angular\src\app\app.component.css:20:30)
    at C:\repo\web-app-angular\src\app\app.component.css:69:18
    at C:\repo\web-app-angular\src\app\app.component.css:72:10
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at Object.runInNewContext (vm.js:135:38)
    at WebpackResourceLoader._evaluate (C:\repo\web-app-angular\node_modules\@ngtools\webpack\src\resource_loader.js:110:40)
    at compilation.plugin (C:\repo\web-app-angular\node_modules\@ngtools\webpack\src\resource_loader.js:58:26)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\repo\web-app-angular\node_modules\webpack\node_modules\tapable\lib\HookCodeFactor
y.js:24:12), <anonymous>:7:1)
```

**The config:**
```js
//Loaders
[{
    test: /\.css$/,
    use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: ['css-loader', 'postcss-loader']
    }),
    exclude: helpers.exclude
},
{
    test: /\.less$/,
    use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: ['css-loader', 'postcss-loader', 'less-loader']
    }),
    exclude: helpers.exclude
}]
// Plugin
new ExtractTextPlugin({
    filename: '[name].[hash].css',
    allChunks: true
})

```
**The component:**
```js
import { Component } from '@angular/core';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent {
    title = 'app';
}
```
**However, when importing the file instead, it works:**
```js
import { Component } from '@angular/core';
import * as style from './app.component.css';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styles: style
})
export class AppComponent {
    title = 'app';
}
```

Even more interesting is that it seems to work in angular5-starter.

```js
//webpack.base.js
[
    {
        test: /\.css$/,
        use: ['to-string-loader', 'css-loader', 'postcss-loader'],
        exclude: [helpers.root('src', 'styles')]
    },
    {
        test: /\.scss$/,
        use: ['to-string-loader', 'css-loader', 'postcss-loader', 'sass-loader'],
        exclude: [helpers.root('src', 'styles')]
    }
]

//webpack.prod.js
[
    {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: 'css-loader!postcss-loader'
        }),
        include: [helpers.root('src', 'styles')]
    },
    {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: 'css-loader!postcss-loader!sass-loader'
        }),
        include: [helpers.root('src', 'styles')]
    }
]
// Plugin
new ExtractTextPlugin('[name].[contenthash].css')
```

Any idea whats happening here?

**Comment by michael-ciniawsky** [comment]
`webpack` works by parsing `import/require` statements and as no context about how a specific frameworks deals with style handling :).
