### ISSUE TITLE
TypeError: Cannot read property 'thisCompilation' of undefined at ExtractTextPlugin.apply

### ISSUE THREAD

**Issue by kuipumu** [webpack-contrib/extract-text-webpack-plugin#753]
Im getting this error at running webpack 

TypeError: Cannot read property 'thisCompilation' of undefined
    at ExtractTextPlugin.apply (C:\Paginas Web\Oricao\node_modules\extract-text-webpack-plugin\dist\index.js:183:20)
    at Compiler.apply (C:\Paginas Web\Oricao\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (C:\Paginas Web\Oricao\node_modules\webpack\lib\webpack.js:33:19)
    at processOptions (C:\Paginas Web\Oricao\node_modules\webpack\bin\webpack.js:335:15)
    at yargs.parse (C:\Paginas Web\Oricao\node_modules\webpack\bin\webpack.js:397:2)
    at Object.Yargs.self.parse (C:\Paginas Web\Oricao\node_modules\yargs\yargs.js:533:18)
    at Object.<anonymous> (C:\Paginas Web\Oricao\node_modules\webpack\bin\webpack.js:152:7)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

I have webpack 3

    "webpack": "^3.11.0",
    "webpack-cli": "^2.0.12"

I tried running from local or global package and still the same, I also don't know why when I run webpack, it keeps asking to install webpack-cli, I read it was because the new webpack 4 version but I have 3 installed.

**Comment by eakarpov** [comment]
I ran into the same problem.
What is your version of the plugin? The fourth major version branch is compatible only with webpack 4. It is a breaking change.
So if you have 4.0.0-beta version of the plugin, just regrade to the 3.0.2 version.

**Comment by ooflorent** [comment]
v4 of this plugin is not compatible with webpack v3. 

- If you are using `webpack@3`, use `extract-text-webpack-plugin@^3.0.2`
- If you are using `webpack@4`, use `mini-css-extract-plugin` if applicable
