### ISSUE TITLE
Webpack 4

### ISSUE THREAD

**Issue by romariolopezc** [webpack-contrib/extract-text-webpack-plugin#760]
```bash
node:38634) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Node#moveTo was deprecated. Use Container#append.
/Users/romario/Repos/personal/elm-webpack-4/node_modules/webpack/lib/Chunk.js:460
		throw new Error(
		^

Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (/Users/romario/Repos/personal/elm-webpack-4/node_modules/webpack/lib/Chunk.js:460:9)
    at /Users/romario/Repos/personal/elm-webpack-4/node_modules/extract-text-webpack-plugin/dist/index.js:176:47
    at Array.forEach (<anonymous>)
    at /Users/romario/Repos/personal/elm-webpack-4/node_modules/extract-text-webpack-plugin/dist/index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/romario/Repos/personal/elm-webpack-4/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/romario/Repos/personal/elm-webpack-4/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/Users/romario/Repos/personal/elm-webpack-4/node_modules/webpack/lib/Compilation.js:881:27)
    at hooks.make.callAsync.err (/Users/romario/Repos/personal/elm-webpack-4/node_modules/webpack/lib/Compiler.js:480:17)
    at _done (eval at create (/Users/romario/Repos/personal/elm-webpack-4/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:9:1)
    at _err1 (eval at create (/Users/romario/Repos/personal/elm-webpack-4/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:32:22)
    at _addModuleChain (/Users/romario/Repos/personal/elm-webpack-4/node_modules/webpack/lib/Compilation.js:749:12)
    at processModuleDependencies.err (/Users/romario/Repos/personal/elm-webpack-4/node_modules/webpack/lib/Compilation.js:688:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c webpack
```

```js
          use: ExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: ['css-loader', 'postcss-loader', 'sass-loader']
          })
```

```js
      new ExtractTextPlugin({
        filename: 'static/css/[name]-[hash].css'
      }),
```

**Comment by romariolopezc** [comment]
There's already an issue: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701

**Comment by trollepierre** [comment]
https://github.com/webpack-contrib/extract-text-webpack-plugin#usage
