### ISSUE TITLE
Error contenthash not implemented with webpack > 4.3.0

### ISSUE THREAD

**Issue by ShinyChang** [webpack-contrib/extract-text-webpack-plugin#765]
**Env:**
Node: 8.9.4
Yarn: 1.5.1
webpack: 4.3.0 & 4.4.0 (NB: 4.1.1 works fine)
extract-text-webpack-plugin: 4.0.0-beta.0
webpack mode: production (NB: dev works fine)
webpack target: web

**Error message**
```
Error: Path variable [contenthash] not implemented in this context: [name]-[contenthash].css
    at fn (project/node_modules/webpack/lib/TemplatedPathPlugin.js:43:11)
    at fn (project/node_modules/webpack/lib/TemplatedPathPlugin.js:31:16)
    at String.replace (<anonymous>)
    at replacePathVariables (project/node_modules/webpack/lib/TemplatedPathPlugin.js:98:5)
    at SyncWaterfallHook.eval [as call] (eval at create (project/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:7:16)
    at MainTemplate.getAssetPath (project/node_modules/webpack/lib/MainTemplate.js:387:31)
    at Compilation.getPath (project/node_modules/webpack/lib/Compilation.js:1798:28)
    at getPath (project/node_modules/extract-text-webpack-plugin/dist/index.js:315:51)
    at ExtractTextPlugin.extractedChunks.forEach.extractedChunk (project/node_modules/extract-text-webpack-plugin/dist/index.js:323:83)
    at Array.forEach (<anonymous>)
    at compilation.hooks.additionalAssets.tapAsync.assetCb (project/node_modules/extract-text-webpack-plugin/dist/index.js:301:25)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (project/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (project/node_modules/webpack/lib/Compilation.js:946:32)
    at _err0 (eval at create (project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _async2.default.forEach.err (project/node_modules/extract-text-webpack-plugin/dist/index.js:296:11)
    at project/node_modules/async/dist/async.js:473:16
    at iteratorCallback (project/node_modules/async/dist/async.js:1050:13)
    at project/node_modules/async/dist/async.js:958:16
    at _async2.default.forEach.err (project/node_modules/extract-text-webpack-plugin/dist/index.js:274:13)
    at project/node_modules/async/dist/async.js:473:16
    at iteratorCallback (project/node_modules/async/dist/async.js:1050:13)
    at project/node_modules/async/dist/async.js:958:16
    at _async2.default.forEach (project/node_modules/extract-text-webpack-plugin/dist/index.js:268:20)
    at project/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (project/node_modules/async/dist/async.js:1055:9)
    at eachOf (project/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (project/node_modules/async/dist/async.js:3158:5)
    at _async2.default.forEach (project/node_modules/extract-text-webpack-plugin/dist/index.js:226:27)
    at project/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (project/node_modules/async/dist/async.js:1055:9)
    at eachOf (project/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (project/node_modules/async/dist/async.js:3158:5)
    at compilation.hooks.optimizeTree.tapAsync (project/node_modules/extract-text-webpack-plugin/dist/index.js:221:25)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (project/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (project/node_modules/tapable/lib/Hook.js:35:21)
```

Not sure this issue should be report here or webpack.

**Comment by evilebottnawi** [comment]
@ShinyChang don't use `ETWP` plugin for extract CSS for `webpack@4`. Use https://github.com/webpack-contrib/mini-css-extract-plugin for extract css.
