### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by Hallya** [webpack-contrib/extract-text-webpack-plugin#780]
Hi, 
It seems the package isn't up to date, here's the webpack deprecation trace: 
```
npm run build

> mws-restaurant-stage-1@1.0.0 build /Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1
> webpack --mode production

clean-webpack-plugin: /Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/dist has been removed.
(node:65771) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at ExtractTextPlugin.apply (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/extract-text-webpack-plugin/dist/index.js:147:16)
    at webpack (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/lib/webpack.js:37:12)
    at processOptions (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/bin/webpack.js:436:16)
    at yargs.parse (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Object.parse (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/node_modules/yargs/yargs.js:552:18)
    at /Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack-cli/bin/webpack.js:514:3)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/dulac/Desktop/CloudStation/WebWork/Udacity/mws-restaurant-stage-1/node_modules/webpack/bin/webpack.js:80:2)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```
And here's my webpack config file:
```
module: {
    rules: [
      {
        test: /\.(js)$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader"
        }
      },
      {
        test: /\.(html)$/,
        use: [{
          loader: 'html-loader',
          options: {
            minimize: false
          }
        }]
      },
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: "css-loader"
        })
      }
    ],
  },
  plugins: [
    new CleanWebpackPlugin(['dist']),
    new ServiceWorkerWebpackPlugin({
      entry: path.join(__dirname, 'dev/sw.js')
    }),
    new HtmlWebpackPlugin({
      template: 'dev/index.html',
      prefetch: [
        '...',
      ],
      preload: [
        '...',
      ],
    }),
    new HtmlWebpackPlugin({
      filename: 'restaurant.html',
      template: 'dev/restaurant.html',
      prefetch: [
        '...',
      ],
      preload: [
        '...',
      ],
    }),
    new ResourceHintWebpackPlugin(),
    new ExtractTextPlugin('dev/assets/css/styles.css'),
    new StyleExtHtmlWebpackPlugin({
      enable: true,
      position: 'head-bottom',
      minify: true
    }),
  ],
```
Am I doing something wrong ?

**Comment by evilebottnawi** [comment]
@Hallya don't use this plugin for extract css, use https://github.com/webpack-contrib/mini-css-extract-plugin

**Comment by Hallya** [comment]
Does it work with [style-ext-html-webpack-plugin](https://www.npmjs.com/package/style-ext-html-webpack-plugin) ?

**Comment by evilebottnawi** [comment]
@Hallya should works

**Comment by evilebottnawi** [comment]
@Hallya Feel free to ping me here if you have problem. Thanks!
