### ISSUE TITLE
"extract-text-webpack-plugin" loader is used without the corresponding plugin

### ISSUE THREAD

**Issue by gabosvk** [webpack-contrib/extract-text-webpack-plugin#812]
Hi,
my production builds suddenly stopped to work. I haven done any updates or something and ended up with below error. I'm using Angular 5 having webpack 3.6.0, production build with AOT. 

`ERROR in Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example at Object.pitch (/Users/.../node_modules/extract-text-webpack-plugin/dist/loader.js:53:11)`

Here is my production config file:

```
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const path = require('path');
const ngToolsWebpack = require('@ngtools/webpack');

const ENV = process.env.NODE_ENV = process.env.ENV = 'prod';


module.exports = {
    entry: {
        'polyfills': './polyfills.ts',
        'vendor': './vendor.ts',
        'app': './app/main-aot.ts'
    },
    resolve: {
        extensions: ['.ts', '.js', '.json']
    },
    output: {
        path: path.join(__dirname, 'wwwroot'),
        filename: 'js/[name].[hash:6].bundle.js',
        chunkFilename: 'js/[id].[hash:6].chunk.js'
    },
    module: {
        rules: [
            {
                test: /\.ts$/,
                use: '@ngtools/webpack'
            },
            {
                test: /\.html$/,
                use: 'html-loader'
            },
            // {
            //     test: /\.(png|jpg|gif|ico|woff|woff2|ttf|svg|eot)$/,
            //     use: 'file-loader?name=assets/[name]-[hash:6].[ext]',
            // },
            {
                test: /\.(png|jpe?g|gif|ico)$/,
                use: 'file-loader?name=assets/[name].[ext]',
            },
            { test: /\.(woff2?|ttf|eot|svg)$/,
                use: 'url-loader'
            },
            {
                test: /\.css$/,
                exclude: path.resolve(__dirname, "app"),
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader', use: [
                        { loader: 'css-loader', options: { minimize: true } }
                    ]
                })
            },
            {
                test: /\.css$/,
                include: path.resolve(__dirname, "app"),
                use: 'raw-loader'
            }
        ]
    },
    plugins: [
        // AoT plugin.
        new ngToolsWebpack.AngularCompilerPlugin({
            tsConfigPath: './tsconfig-aot.json'
        }),
        new webpack.optimize.ModuleConcatenationPlugin(),
        new webpack.optimize.CommonsChunkPlugin({
            name: ['app', 'vendor', 'polyfills']
        }),
        new CleanWebpackPlugin(
            [
                './wwwroot/js/',
                './wwwroot/css/',
                './wwwroot/assets/',
                './wwwroot/index.html'
            ]
        ),
        new CopyWebpackPlugin([
            { from: './assets', to: './assets' },
        ]),
        // inject in index.html
        new HtmlWebpackPlugin({
            template: './index.html',
            inject: 'body',
            filename: 'index.html'
        }),
        new ExtractTextPlugin('css/[name]-[hash:6].bundle.css'),
        new webpack.DefinePlugin({
            'process.env': {
                'ENV': JSON.stringify('prod')
            }
        }),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            },
            output: {
                comments: false
            },
            sourceMap: false
        }),
        new webpack.ProvidePlugin({
            jQuery: 'jquery',
            $: 'jquery',
            jquery: 'jquery'
        })
    ]
};
```

I'm running the following command to build my project:
`rm -rf .aot wwwroot node_modules/ && npm cache clean -f && npm install && npm run ngc && npm run build:dist`

Also posting my package.json:
```
{
  "name": "myapp",
  "version": "1.2.3",
  "description": "myappdesc",
  "repository": {},
  "scripts": {
    "ngc": "ngc -p ./tsconfig-aot.json",
    "start": "concurrently \"webpack-dev-server --env=dev --hot --inline --host 127.0.0.1 --port 3000 --open\" \"dotnet run\" ",
    "build:dev": "webpack --env=dev --progress --profile --colors",
    "build:dist": "webpack --env=prod --progress --profile --colors",
    "lint": "tslint ./app/**/*.ts -t verbose",
    "tsc": "tsc",
    "tsc:w": "tsc -w"
  },
  "license": "MIT",
  "dependencies": {
    "@agm/core": "1.0.0-beta.3",
    "@angular/animations": "5.2.10",
    "@angular/common": "5.2.10",
    "@angular/compiler": "5.2.10",
    "@angular/core": "5.2.10",
    "@angular/forms": "5.2.10",
    "@angular/http": "5.2.10",
    "@angular/platform-browser": "5.2.10",
    "@angular/platform-browser-dynamic": "5.2.10",
    "@angular/router": "5.2.10",
    "@angular/upgrade": "5.2.10",
    "@angularclass/hmr": "2.1.3",
    "@swimlane/ngx-charts": "7.4.0",
    "@types/jquery": "^3.2.17",
    "angular-calendar": "^0.24.0",
    "angular2-moment": "^1.8.0",
    "angular2-text-mask": "^8.0.4",
    "angular2-uuid": "^1.1.1",
    "angularfire2": "5.0.0-rc.6.0",
    "angulartics2": "5.3.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "firebase": "4.12.1",
    "font-awesome": "^4.7.0",
    "ie-shim": "~0.1.0",
    "jquery": "^3.2.1",
    "moment": "^2.18.1",
    "moment-timezone": "^0.5.14",
    "ng2-file-upload": "1.3.0",
    "ng2-select": "2.0.0",
    "ngx-bootstrap": "2.0.3",
    "ngx-infinite-scroll": "^0.5.1",
    "ngx-slick": "^0.1.3",
    "ngx-toastr": "8.4.0",
    "ngx-uploader": "^4.3.0",
    "promise-polyfill": "^6.0.2",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.5.2",
    "slick-carousel": "1.8.1",
    "text-mask-core": "^5.0.1",
    "traceur": "^0.0.96",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "5.2.10",
    "@ngtools/webpack": "1.10.2",
    "@types/core-js": "^0.9.34",
    "@types/googlemaps": "^3.26.1",
    "@types/jasmine": "^2.5.54",
    "@types/moment-timezone": "^0.5.3",
    "@types/node": "8.0.26",
    "angular-router-loader": "^0.6.0",
    "angular2-template-loader": "^0.6.2",
    "awesome-typescript-loader": "^3.2.3",
    "canonical-path": "0.0.2",
    "clean-webpack-plugin": "^0.1.16",
    "codelyzer": "^3.1.2",
    "concurrently": "^3.5.0",
    "copy-webpack-plugin": "^4.2.0",
    "css-loader": "^0.28.7",
    "css-to-string-loader": "^0.1.3",
    "extract-loader": "^1.0.1",
    "mini-css-extract-plugin": "^0.4.4",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.5",
    "html-loader": "^0.5.1",
    "html-webpack-plugin": "^2.30.1",
    "http-server": "^0.10.0",
    "json-loader": "^0.5.7",
    "lite-server": "^2.3.0",
    "lodash": "^4.17.4",
    "node-sass": "^4.5.3",
    "protractor": "~5.1.2",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.6.1",
    "sass-loader": "^6.0.6",
    "source-map-loader": "^0.2.1",
    "style-loader": "^0.18.2",
    "to-string-loader": "^1.1.5",
    "ts-helpers": "^1.1.2",
    "tslint": "^5.7.0",
    "tslint-loader": "^3.5.3",
    "typescript": "2.8.3",
    "typings": "^2.1.1",
    "url-loader": "^0.5.9",
    "webpack": "^3.6.0",
    "webpack-dev-server": "^2.9.1"
  },
  "-vs-binding": {
    "BeforeBuild": [
      "build:dev"
    ]
  }
}

```

I'm really hopeless because this started on our PROD environment and we can't go out with update / hotfix.

Thanks.

**Comment by STRsplit** [comment]
It looks like there are some others with this problem in the closed issues:
[Closed issues: 'loader is used without the corresponding plugin'](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues?q=is%3Aissue+loader+is+used+without+the+corresponding+plugin+is%3Aclosed)

This issue in the angular-cli repo also looked very similar:
https://github.com/angular/angular-cli/issues/5628

Hope that helps.

**Comment by abumphy** [comment]
this is my config:

```package.json
"devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "^7.2.3",
    "babel-loader": "^8.0.5",
    "babel-preset-env": "^1.7.0",
    "css-loader": "^2.1.0",
   "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "style-loader": "^0.23.1",
    "webpack": "^4.28.4",
    "webpack-cli": "^3.2.1",
    "webpack-node-externals": "^1.7.2"
  }
```
when I am `npm run build`,throw error:

```cmd
ERROR in ./src/style.css
Module build failed (from ./node_modules/extract-text-webpack-plugin/dist/loader.js):
Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.pitch (/Users/bumphy/Documents/webpack/webpack-simple/node_modules/extract-text-webpack-plugin/dist/loader.js:59:11)
 @ ./src/index.js 3:0-22
```
This is because of the version of webpack.Details are [here](https://github.com/webpack-contrib/extract-text-webpack-plugin#usage)

Since webpack v4 the extract-text-webpack-plugin should not be used for css. Use `mini-css-extract-plugin` instead.

How to config `mini-css-extract-plugin`,you can read the [document](https://github.com/webpack-contrib/mini-css-extract-plugin).

My problem is solved.I hope these help you.

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
