### ISSUE TITLE
Error : TypeError: Object.keys called on non-object

### ISSUE THREAD

**Issue by LeoLeBras** [webpack-contrib/extract-text-webpack-plugin#83]
Hi !
The plugin is throwing an error in index.js line 119 : 

``` javascript
*****\node_modules\extract-text-webpack-plugin\index.js:119
    Object.keys(b).forEach(function(key) {`
               ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at mergeOptions (*****\node_modules\extract-text-webpack-plugin\index.js:119:9)
    at Function.ExtractTextPlugin.extract (*****\node_modules\extract-text-webpack-plugin\index.js:132:29)
    at Object.<anonymous> (*****\webpack.config.js:36:39)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! react-hot-boilerplate@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-hot-boilerplate@1.0.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the react-hot-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-hot-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     *****\npm-debug.log

```

My webpack.config : 

``` javascript
var path = require('path'),
    webpack = require('webpack'),
    NyanProgressPlugin = require('nyan-progress-webpack-plugin'),
    ExtractTextPlugin = require('extract-text-webpack-plugin'),
    autoprefixer = require('autoprefixer-core');

module.exports = {
    server: {
        port: 3000,
        url: 'localhost',
        hot: true,
        historyApiFallback: true,
        contentBase: './src/'
    },
    devtool: 'eval',
    entry: [
        'webpack-dev-server/client?http://localhost:3000',
        'webpack/hot/only-dev-server',
        './src/js/index'
    ],
    output: {
        path: path.join(__dirname, 'build'),
        filename: 'index.js',
        publicPath: '/__build__/'
    },
    resolve: {
        extensions: ['', '.js', '.jsx', '.css']
    },
    module: {
        loaders: [{
            test: /\.jsx?$/,
            loaders: ['react-hot', 'babel'],
            include: path.join(__dirname, 'src/js')
        },{
            test: /\.css$/,
            loader: ExtractTextPlugin.extract('style-loader', 'css-loader', 'postcss-loader')
        }]
    },
    postcss: function(){
        return [autoprefixer];
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin(),
        new NyanProgressPlugin(),
        new ExtractTextPlugin("styles.css")
    ]
};
```

It's react-hot-loader or extract-text-webpack-plugin? Without extract-text-webpack-plugin, there are no bug problems.

Help me ! :)

**Comment by JuoCode** [comment]
@LeoLeBras I have same problem, are you solve it?

**Comment by LeoLeBras** [comment]
Yes but I absolutely don't remember how ... Sorry ! :/ 
My webpack config (work in progress) if it helps you : 
````
var path = require('path'),
    webpack = require('webpack'),
    ExtractTextPlugin = require('extract-text-webpack-plugin'),
    NyanProgressPlugin = require('nyan-progress-webpack-plugin');

module.exports = {
    server: {
        port: 3000,
        url: 'localhost',
        hot: true,
        historyApiFallback: true,
    },
    devtool: 'eval',
    entry: [
        'webpack-dev-server/client?http://localhost:3000',
        'webpack/hot/only-dev-server',
        './src/index'
    ],
    output: {
        path: path.join(__dirname, '__build__'),
        filename: 'index.js',
        publicPath: '/__build__/'
    },
    resolve: {
        extensions: ['', '.js', '.jsx', '.scss', 'ts'],
        modulesDirectories: [
            'src/web_modules',
            'node_modules',
            'src/assets',
            'src/scripts',
            'src/scripts/containers'
        ]
    },
    module: {
        loaders: [{
            test: /\.jsx?$/,
            loaders: ['react-hot', 'babel'],
            include: path.join(__dirname, 'src')
        },{
            test: /\.ts$/,
            loader: 'typescript-loader'
        },{
            test: /\.(scss|css)$/,
            loader: ExtractTextPlugin.extract('style', 'css!postcss!sass?outputStyle=expanded&' +
                      'includePaths[]=' +
                        (path.resolve(__dirname, './src/assets/fonts/')) + '&' +
                      'includePaths[]=' +
                        (path.resolve(__dirname, './src/assets/stylesheets/')))
        },{
            test: /.*\.(gif|png|jpe?g|svg)$/i,
            loaders: [
              'file?hash=sha512&digest=hex&name=[hash].[ext]',
              'image-webpack?{progressive:true, optimizationLevel: 7, interlaced: false, pngquant:{quality: "65-90", speed: 4}}'
            ]
        },{
            test: /.*\.(ttf|woff)$/i,
            loader: 'file'
        }]
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin(),
        new NyanProgressPlugin(),
        new ExtractTextPlugin('style.css', {disable: true})
    ],
    postcss : function(){
        var pxtorem = require('postcss-pxtorem');
        return [
            pxtorem({
                media_query: true,
                prop_white_list: ['font-size', 'line-height', 'letter-spacing', 'margin',
                    'margin-top', 'margin-right', 'margin-bottom', 'margin-left', 'padding',
                    'padding-top', 'padding-right', 'padding-bottom', 'padding-left', 'width',
                    'height', 'top', 'left', 'bottom', 'right', 'border-radius', 'border',
                    'border-top', 'border-right', 'border-bottom', 'border-left', 'max-width',
                    'max-height', 'background-size', 'background-position', 'transform']
        })];
    }

};
```

**Comment by stevenjlho** [comment]
I have same problem. I found that this error happens when i use sass loader.

**Comment by idiotstrike** [comment]
Same problem here, happens with the sass loader

**Comment by LeoLeBras** [comment]
I had this problem with postcss, it's not only happens with the sass loader.

**Comment by rkoberg** [comment]
I had to remove the style loader - `ExtractTextPlugin.extract('css?sourceMap!sass?sourceMap'),`:
```

if(TARGET === 'build') {
  module.exports = merge(common, {
....
    plugins: [
      new ExtractTextPlugin('styles.css'),
     ....
    ],
    module: {
      loaders: [
        {
          test: /\.scss$/,
          loader: ExtractTextPlugin.extract('css?sourceMap!sass?sourceMap'),
          include: path.resolve(ROOT_PATH, 'app')
        },
       ...
      ]
    }
  });
}
```

**Comment by stevenjlho** [comment]
It works. I find that must be use this style. if you write code below, it can't work.

     ExtractTextPlugin.extract('style-loader', 'css-loader', 'sass-loader')

**Comment by nightgrey** [comment]
I also have this problem when using the ExtractTextPlugin.

**Console log** (replaced project name with ***)
```
> ***@1.0.0 build D:\workspace\***
> SET TARGET=build&& webpack

D:\workspace\***\node_modules\extract-text-webpack-plugin\index.js:119
        Object.keys(b).forEach(function(key) {
               ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at mergeOptions (D:\workspace\***\node_modules\extract-text-webpack-plugin\index.js:119:9)
    at Function.ExtractTextPlugin.extract (D:\workspace\***\node_modules\extract-text-webpack-plugin
\index.js:132:29)
    at Object.<anonymous> (D:\workspace\***\webpack.config.js:117:32)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (D:\workspace\***\node_modules\webpack\bin\convert-argv.js:80:13)
    at Object.<anonymous> (D:\workspace\***\node_modules\webpack\bin\webpack.js:54:40)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "r
un" "build"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! ***@1.0.0 build: `SET TARGET=build&& webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ***@1.0.0 build script 'SET TARGET=build&& webpack'.
npm ERR! This is most likely a problem with the *** package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     SET TARGET=build&& webpack
npm ERR! You can get their info via:
npm ERR!     npm owner ls ***
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\workspace\***\npm-debug.log
```

**npm-debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild ***@1.0.0
6 info build ***@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info ***@1.0.0 Failed to exec build script
9 verbose stack Error: ***@1.0.0 build: `SET TARGET=build&& webpack`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid ***@1.0.0
11 verbose cwd D:\workspace\***
12 error Windows_NT 6.3.9600
13 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error ***@1.0.0 build: `SET TARGET=build&& webpack`
17 error Exit status 1
18 error Failed at the ***@1.0.0 build script 'SET TARGET=build&& webpack'.
18 error This is most likely a problem with the *** package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     SET TARGET=build&& webpack
18 error You can get their info via:
18 error     npm owner ls ***
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**webpack.config.js** (I'm only using the ExtractTextPlugin for building, not for developing)
```js
var webpack = require('webpack'),
	path = require('path'),
	merge = require('webpack-merge'),
	htmlWebpackPlugin = require('html-webpack-plugin'),
	cleanWebpackPlugin = require('clean-webpack-plugin'),
	extractTextWebpackPlugin = require('extract-text-webpack-plugin'),
	package = require('./package.json');



/**
 * Environment variables
 */
var TARGET = process.env.TARGET;
var ROOT_PATH = path.resolve(__dirname);



/**
 * Common HTML webpack plugin confgiuration
 * @type {Object}
 */
var htmlWebPackPluginConfiguration = {
	title: 'Klinik App',
	template: path.resolve(ROOT_PATH, 'app/template.html'),
}



/**
 * Common configuration object
 */
var commonConfiguration = {
	entry: path.resolve(ROOT_PATH, 'app/main.js'),
	output: {
		path: path.resolve(ROOT_PATH, 'build'),
		filename: 'bundle.js'
	},
	module: {
		loaders: [
			{
				test: /\.(jpe?g|png|gif|svg)$/i,
				loaders: [
					'url-loader?limit=30000&name=[name].[ext]',
					'image-webpack?{progressive:false, optimizationLevel: 7, interlaced: true,}'
				],
				include: path.resolve(ROOT_PATH, 'app/images')
			},
			{
				test: /\.(eot|svg|ttf|woff)$/,
				loader: 'url-loader?limit=30000&name=[name].[ext]',
				include: path.resolve(ROOT_PATH, 'app/library')
			}
		]
	},
	plugins: [
		new htmlWebpackPlugin(htmlWebPackPluginConfiguration),
	]
};



/**
 * Developement configuration
 */
if(TARGET === 'dev') {
	module.exports = merge(commonConfiguration, {
		devtool: 'eval',
		module: {
			loaders: [
				{
					test: /\.css$/,
					loaders: [
						'style-loader',
						'css-loader',
						'autoprefixer-loader?{browsers: ["iOS > 7", "Android > 3", "last 3 ChromeAndroid versions"], cascade: false}'
					],
					include: path.resolve(ROOT_PATH, 'app')
				},
				{
					test: /\.js$/,
					loaders: ['react-hot-loader', 'babel-loader'],
					include: path.resolve(ROOT_PATH, 'app')
				}
			]
		}
	});
}



/**
 * Build configuration
 */
if(TARGET === 'build') {
	htmlWebPackPluginConfiguration = merge(htmlWebPackPluginConfiguration, {
		minify: {
			removeComments: true,
			collapseWhitespace: true
		}
	});

	module.exports = merge(commonConfiguration, {
		entry: {
			app: path.resolve(ROOT_PATH, 'app/main.js'),
			vendor: Object.keys(package.dependencies)
		},
		output: {
			path: path.resolve(ROOT_PATH, 'build'),
			filename: 'app.js'
		},
		devtool: 'source-map',
		module: {
			loaders: [
				{
					test: /\.css$/,
					loader: extractTextWebpackPlugin.extract('style-loader', 'css-loader', 'autoprefixer-loader?{browsers: ["iOS > 7", "Android > 3", "last 3 ChromeAndroid versions"], cascade: false}'),
					include: path.resolve(ROOT_PATH, 'app')
				},
				{
					test: /\.js$/,
					loaders: ['babel-loader'],
					include: path.resolve(ROOT_PATH, 'app')
				}
			]
		},
		plugins: [
			new cleanWebpackPlugin(['build']),
			new webpack.optimize.DedupePlugin(),
			new webpack.optimize.CommonsChunkPlugin(
				'vendor', 'vendor.js'
			),
			new webpack.DefinePlugin({
				'process.env': {
					'NODE_ENV': JSON.stringify('production')
				}
			}),
			new webpack.optimize.UglifyJsPlugin({
				compress: {
					warnings: false,
					screw_ie8: true
				},
				output: {
					comments: false
				}
			}),
			new extractTextWebpackPlugin('main.css'),
			new htmlWebpackPlugin(htmlWebPackPluginConfiguration)
		]
	});
}
```

If I remove autoprefixer-loader it works, but that shouldn't be, shouldn't it? Does anyone have a solution?

**Comment by nightgrey** [comment]
Guys, I have a solution, but I really do not know why it actually works.

What I did was changing the arguments in the extractTextWebpackPlugin.extract() function in my webpack.config.js (seen in the post above) from this (doesn't work)

```js
loader: extractTextWebpackPlugin.extract('style-loader', 'css-loader', 'autoprefixer-loader?{browsers: ["iOS > 7", "Android > 3", "last 3 ChromeAndroid versions"], cascade: false}'),
```

to this (works)

```js
loader: extractTextWebpackPlugin.extract('style-loader', 'css-loader!autoprefixer-loader?{browsers: ["iOS > 7", "Android > 3", "last 3 ChromeAndroid versions"], cascade: false}'),
```

Could some with more in-depth understanding of webpack explain this? Why does this work and the other notation doesn't? If I had to guess I'd say it has something to do with how webpack or the extract text plugin executes and/or handles the loaders.

**Comment by bebraw** [comment]
@nightgrey The latter form is correct. Looks like it all stems from [the function definition](https://github.com/webpack/extract-text-webpack-plugin/blob/dc353ee5791b5ece9488d8321c79d89b0d806984/index.js#L129). It expects `options` object as its third parameter.

I opened a related issue (#94). I think we can make the interface more generic to avoid the problem. Just need to do a little type check. That's all.

Btw you can figure out `TARGET` in a nicer way like this:

> var TARGET = process.env.npm_lifecycle_event;

After that you can drop `TARGET` definition from *package.json*. You will have to tweak the if statements to operate based on npm script names but apart from that this is a superior solution. I found it a while ago and updated the book accordingly.

**Comment by adrianolaru** [comment]
It works if you just use something like this:

```
loader: ExtractTextPlugin.extract('style', 'css!postcss')
```

where you first declare the first loader, then the others as a chain of loaders.

**Comment by bebraw** [comment]
@adrianolaru Yeah. That's what #94 is about. I think we can make it accept what most people might expect or at the very least it could emit a useful warning. :+1:

**Comment by stenmuchow** [comment]
@adrianolaru @bebraw - thanks guys! wish your comments were at the top of this thread...

**Comment by bebraw** [comment]
The API should be far clearer now. Closing.
